const itemDBJSON = `{
  "item_stomahawk": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_stomahawk",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 6,
    "name": "Stone Tomahawk",
    "level": 5,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_throwingaxe_03",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 3,
    "type": "weapon",
    "val": 25
  },
  "item_lumberaxe": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_lumberaxe",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 13,
    "name": "Lumberjack Axe",
    "level": 9,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_axe_01",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 7,
    "type": "weapon",
    "val": 113
  },
  "item_pumpkin": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_pumpkin",
    "mat": "none",
    "dropstackmax": 1,
    "abil": "abil_pumpkin",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Country Pumpkin",
    "level": 11,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_food_25",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 10
  },
  "item_lknapsack": {
    "slots": 12,
    "quality": "common",
    "loc": "none",
    "id": "item_lknapsack",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Large Knapsack",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_bag_07_red",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "bag",
    "val": 1800
  },
  "item_maestragloves": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "gloves",
    "id": "item_maestragloves",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "sta",
        "num": 3
      },
      {
        "stat": "int",
        "num": 3
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Maestra's Gloves",
    "level": 9,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_gauntlets_29",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 63,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 520
  },
  "item_milk": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_milk",
    "mat": "none",
    "dropstackmax": 1,
    "abil": "abil_milk",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Ice Cold Milk",
    "level": 1,
    "droprate": 100,
    "clas": "shaman",
    "icon": "Inv_drink_milk_01",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 6
  },
  "item_scoutmedallion": {
    "slots": 0,
    "quality": "rare",
    "loc": "neck",
    "armor": 0,
    "mat": "none",
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 6
      },
      {
        "stat": "sta",
        "num": 2
      }
    ],
    "effects": [],
    "id": "item_scoutmedallion",
    "name": "Scout's Medallion",
    "level": 7,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_jewelry_necklace_14",
    "dropstackmin": 1,
    "worlddrop": true,
    "dmgmax": 0,
    "dropstackmax": 1,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 320
  },
  "item_cookiemallet": {
    "slots": 0,
    "quality": "rare",
    "loc": "none",
    "id": "item_cookiemallet",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "str",
        "num": 3
      },
      {
        "stat": "sta",
        "num": 3
      }
    ],
    "effects": [],
    "dmgmax": 30,
    "name": "Cookie's Meat Mallet",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_hammer_09",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 10,
    "type": "weapon",
    "val": 1639
  },
  "item_minormanapot": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_minormanapot",
    "mat": "none",
    "dropstackmax": 1,
    "abil": "abil_item_minormanapot",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Minor Mana Potion",
    "level": 1,
    "droprate": 3,
    "clas": "shaman",
    "icon": "Inv_potion_70",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 120
  },
  "item_sulfuras": {
    "quality": "legendary",
    "powermod": 0,
    "id": "item_sulfuras",
    "target": "none",
    "clas": "default",
    "stats": [
      {
        "stat": "str",
        "num": 12
      },
      {
        "stat": "sta",
        "num": 12
      }
    ],
    "effects": [],
    "armor": 0,
    "level": 80,
    "stack": 1,
    "cures": "none",
    "val": 1061408,
    "slots": 0,
    "sfx": "none",
    "loc": "none",
    "mat": "none",
    "dmgmin": 223,
    "dmgmax": 372,
    "name": "Sulfuras, Hand of Ragnaros",
    "hpmod": 0,
    "incombat": true,
    "icon": "Inv_hammer_unique_sulfuras",
    "outcombat": true,
    "dropstackmax": 1,
    "droprate": 0,
    "worlddrop": false,
    "desc": "",
    "dropstackmin": 1,
    "type": "weapon"
  },
  "item_cloakcourage": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "back",
    "id": "item_cloakcourage",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "str",
        "num": 1
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Cloak of Courage",
    "level": 11,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_cape_18",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 18,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 96
  },
  "item_sweetpotato": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_sweetpotato",
    "mat": "none",
    "dropstackmax": 2,
    "abil": "abil_sweetpotato",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Sweet Potato",
    "level": 8,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_herb_07",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 4
  },
  "item_flashbomb": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "armor": 0,
    "mat": "none",
    "abil": "abil_flashbomb",
    "stats": null,
    "effects": null,
    "id": "item_flashbomb",
    "name": "Flash Bomb",
    "level": 1,
    "droprate": 100,
    "stack": 20,
    "icon": "Inv_misc_ammo_bullet_01",
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "type": "consumable",
    "worlddrop": false,
    "desc": "",
    "clas": "default",
    "dmgmin": 0,
    "val": 350
  },
  "item_gnarlshoulders": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "shoulders",
    "id": "item_gnarlshoulders",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "sta",
        "num": 3
      },
      {
        "stat": "int",
        "num": 3
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Gnarlbark Shoulders",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_shoulder_14",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 112,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 716
  },
  "item_crackedlgloves": {
    "slots": 0,
    "quality": "common",
    "loc": "gloves",
    "id": "item_crackedlgloves",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Cracked Leather Gloves",
    "level": 4,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_gauntlets_18",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 20,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 300
  },
  "item_everstillbplate": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "chest",
    "id": "item_everstillbplate",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "sta",
        "num": 3
      },
      {
        "stat": "int",
        "num": 4
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Everstill Breastplate",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_chest_chain_08",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 131,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 620
  },
  "item_scraggylbracers": {
    "slots": 0,
    "quality": "common",
    "loc": "wrist",
    "id": "item_scraggylbracers",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Scraggy Leather Bracers",
    "level": 2,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_bracer_10",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 12,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 9
  },
  "item_tarpdew": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_tarpdew",
    "mat": "none",
    "dropstackmax": 2,
    "abil": "abil_tarpdew",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Tarp Collected Dew",
    "level": 5,
    "droprate": 100,
    "clas": "shaman",
    "icon": "Inv_drink_waterskin_04",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 1
  },
  "item_bardbelt": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "belt",
    "id": "item_bardbelt",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 1
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Bard's Belt",
    "level": 7,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_belt_03",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 39,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 180
  },
  "item_greed": {
    "slots": 0,
    "quality": "epic",
    "loc": "none",
    "id": "item_greed",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 29
      },
      {
        "stat": "sta",
        "num": 10
      }
    ],
    "effects": [
      {
        "value": "eff_greed"
      }
    ],
    "dmgmax": 92,
    "name": "Greed",
    "level": 21,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_weapon_hand_06",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 28,
    "type": "weapon",
    "val": 188047
  },
  "item_q_chunkboar": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_q_chunkboar",
    "mat": "none",
    "dropstackmax": 3,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Chunk of Boar Meat",
    "level": 1,
    "droprate": 90,
    "clas": "default",
    "icon": "Inv_misc_food_14",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "quest",
    "val": 0
  },
  "item_roughwoodstaff": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_roughwoodstaff",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 3,
    "name": "Rough Wooden Staff",
    "level": 2,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_staff_09",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 1,
    "type": "weapon",
    "val": 35
  },
  "item_frogband": {
    "slots": 0,
    "abil": null,
    "desc": "",
    "loc": "ring",
    "armor": 0,
    "mat": "none",
    "quality": "rare",
    "stats": [
      {
        "stat": "agi",
        "num": 20
      },
      {
        "stat": "sta",
        "num": 15
      }
    ],
    "effects": [
      {
        "value": "eff_frogband"
      }
    ],
    "id": "item_frogband",
    "name": "Frog-Toe Band",
    "level": 20,
    "droprate": 100,
    "stack": 1,
    "icon": "Inv_jewelry_ring_44",
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "worlddrop": false,
    "clas": "default",
    "dmgmin": 0,
    "type": "armor",
    "val": 10000
  },
  "item_vigcharm": {
    "slots": 0,
    "quality": "rare",
    "loc": "trinket",
    "id": "item_vigcharm",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [
      {
        "value": "eff_vigcharm"
      }
    ],
    "dmgmax": 0,
    "name": "Vigilance Charm",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_stonetablet_04",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 1612
  },
  "item_blackcutlass": {
    "slots": 0,
    "quality": "rare",
    "loc": "none",
    "id": "item_blackcutlass",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 4
      }
    ],
    "effects": [
      {
        "value": "eff_blackcutlass"
      }
    ],
    "dmgmax": 24,
    "name": "Blackwater Cutlass",
    "level": 13,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_sword_24",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 16,
    "type": "weapon",
    "val": 1736
  },
  "item_raidbelt": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "belt",
    "id": "item_raidbelt",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "sta",
        "num": 2
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Raider's Belt",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_belt_11",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 74,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 312
  },
  "item_raidgauntlets": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "gloves",
    "id": "item_raidgauntlets",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "str",
        "num": 3
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Raider's Gauntlets",
    "level": 11,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_gauntlets_04",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 86,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 358
  },
  "item_bandvigor": {
    "slots": 0,
    "quality": "rare",
    "loc": "ring",
    "id": "item_bandvigor",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "sta",
        "num": 7
      },
      {
        "stat": "str",
        "num": 3
      }
    ],
    "effects": [
      {
        "value": "eff_bandvigor"
      }
    ],
    "dmgmax": 0,
    "name": "Band of Vigor",
    "level": 11,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_jewelry_ring_20",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 2340
  },
  "item_andonisus": {
    "slots": 0,
    "quality": "legendary",
    "loc": "none",
    "id": "item_andonisus",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [
      {
        "value": "eff_andonisus"
      }
    ],
    "dmgmax": 220,
    "name": "Andonisus, Reaper of Souls",
    "level": 21,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_sword_61",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 159,
    "type": "weapon",
    "val": 236090
  },
  "item_runebag": {
    "slots": 14,
    "quality": "common",
    "loc": "none",
    "id": "item_runebag",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Runecloth Bag",
    "level": 13,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_bag_19",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "bag",
    "val": 2150
  },
  "item_newbag": {
    "slots": 20,
    "quality": "epic",
    "loc": "none",
    "id": "item_newbag",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Papa's New Bag",
    "level": 10,
    "droprate": 0,
    "clas": "default",
    "icon": "Inv_misc_bag_26_spellfire",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "bag",
    "val": 8750
  },
  "item_strikhatchet": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_strikhatchet",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 13,
    "name": "Striking Hatchet",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_axe_11",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 6,
    "type": "weapon",
    "val": 12
  },
  "item_tarnishedcgloves": {
    "slots": 0,
    "quality": "common",
    "loc": "gloves",
    "id": "item_tarnishedcgloves",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Tarnished Chain Gloves",
    "level": 4,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_gauntlets_04",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 33,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 410
  },
  "item_manure": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_manure",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Pile of Manure",
    "level": 1,
    "droprate": 70,
    "clas": "default",
    "icon": "Inv_misc_manure",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "quest",
    "val": 0
  },
  "item_bardtunic": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "chest",
    "id": "item_bardtunic",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 4
      },
      {
        "stat": "sta",
        "num": 2
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Bard's Tunic",
    "level": 11,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_shirt_11",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 84,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 610
  },
  "item_augcgloves": {
    "slots": 0,
    "quality": "common",
    "loc": "gloves",
    "id": "item_augcgloves",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Augmented Chain Gloves",
    "level": 7,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_gauntlets_04",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 74,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 396
  },
  "item_bloodvial": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_bloodvial",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Vial of Blood",
    "level": 1,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_potion_50",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 10,
    "desc": "",
    "dmgmin": 0,
    "type": "quest",
    "val": 0
  },
  "item_stonestaff": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "none",
    "id": "item_stonestaff",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "int",
        "num": 2
      }
    ],
    "effects": [],
    "dmgmax": 15,
    "name": "Stonesplinter Staff",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_staff_21",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 8,
    "type": "weapon",
    "val": 512
  },
  "item_heavyhammer": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_heavyhammer",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 5,
    "name": "Heavy Hammer",
    "level": 4,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_hammer_15",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 2,
    "type": "weapon",
    "val": 48
  },
  "item_dmailcoif": {
    "slots": 0,
    "quality": "common",
    "loc": "head",
    "id": "item_dmailcoif",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Double Mail Coif",
    "level": 9,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_helmet_39",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 84,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 275
  },
  "item_imbgcloak": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "back",
    "id": "item_imbgcloak",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "int",
        "num": 1
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Imbued Gypsy Cloak",
    "level": 11,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_cape_17",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 18,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 95
  },
  "item_deathshortsword": {
    "slots": 0,
    "abil": null,
    "loc": "none",
    "armor": 0,
    "mat": "none",
    "quality": "uncommon",
    "stats": [],
    "effects": [],
    "id": "item_deathshortsword",
    "name": "Deathstalker Shortsword",
    "level": 11,
    "droprate": 100,
    "stack": 1,
    "icon": "Inv_sword_15",
    "dropstackmin": 1,
    "dmgmax": 14,
    "dropstackmax": 1,
    "dmgmin": 7,
    "worlddrop": true,
    "desc": "",
    "clas": "default",
    "type": "weapon",
    "val": 188
  },
  "item_lifestone": {
    "slots": 0,
    "quality": "epic",
    "loc": "trinket",
    "id": "item_lifestone",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [
      {
        "value": "eff_lifestone"
      }
    ],
    "dmgmax": 0,
    "name": "Lifestone",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_ore_truesilver_01",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 28000
  },
  "item_chelocuffs": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "wrist",
    "id": "item_chelocuffs",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "int",
        "num": 10
      },
      {
        "stat": "sta",
        "num": 2
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Chelonian Cuffs",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_bracer_06",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 72,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 978
  },
  "item_axesdwarf": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "none",
    "id": "item_axesdwarf",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "str",
        "num": 1
      },
      {
        "stat": "sta",
        "num": 1
      }
    ],
    "effects": [],
    "dmgmax": 17,
    "name": "Battleaxe of the Sober Dwarf",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_axe_09",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "That's an oxymoron, lad.",
    "dmgmin": 8,
    "type": "weapon",
    "val": 302
  },
  "item_shoddycboots": {
    "slots": 0,
    "quality": "common",
    "loc": "boots",
    "id": "item_shoddycboots",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Shoddy Chain Boots",
    "level": 1,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_boots_01",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 28,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 19
  },
  "item_lesserhealpot": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_lesserhealpot",
    "mat": "none",
    "dropstackmax": 1,
    "abil": "abil_lesserhealpot",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Lesser Healing Potion",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_potion_50",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 150
  },
  "item_crackedbill": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_crackedbill",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Cracked Bill",
    "level": 1,
    "droprate": 11,
    "clas": "default",
    "icon": "Inv_misc_birdbeck_01",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "trade",
    "val": 28
  },
  "item_greenpawbelt": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "belt",
    "id": "item_greenpawbelt",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "int",
        "num": 5
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Greenpaw Belt",
    "level": 9,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_belt_23",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 64,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 574
  },
  "item_rcopperbomb": {
    "slots": 0,
    "abil": "abil_rcopperbomb",
    "desc": "",
    "loc": "none",
    "armor": 0,
    "mat": "none",
    "quality": "common",
    "stats": null,
    "effects": null,
    "id": "item_rcopperbomb",
    "name": "Rough Copper Bomb",
    "level": 1,
    "droprate": 100,
    "stack": 20,
    "icon": "Inv_misc_bomb_09",
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "worlddrop": false,
    "clas": "default",
    "dmgmin": 0,
    "type": "consumable",
    "val": 100
  },
  "item_blacksbag": {
    "slots": 10,
    "quality": "common",
    "loc": "none",
    "id": "item_blacksbag",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Black Silk Bag",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_bag_07_black",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "bag",
    "val": 1440
  },
  "item_brokenbottle": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_brokenbottle",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 13,
    "name": "Broken Wine Bottle",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_drink_10",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 6,
    "type": "weapon",
    "val": 234
  },
  "item_flimsycbelt": {
    "slots": 0,
    "quality": "common",
    "loc": "belt",
    "id": "item_flimsycbelt",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Flimsy Chain Belt",
    "level": 2,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_belt_06",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 20,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 16
  },
  "item_giantegg": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_giantegg",
    "mat": "none",
    "dropstackmax": 1,
    "abil": "abil_giantegg",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Giant Egg",
    "level": 1,
    "droprate": 5,
    "clas": "default",
    "icon": "Inv_egg_03",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 30
  },
  "item_augcboots": {
    "slots": 0,
    "quality": "common",
    "loc": "boots",
    "id": "item_augcboots",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Augmented Chain Boots",
    "level": 9,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_boots_01",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 82,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 487
  },
  "item_kmachete": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_kmachete",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 6,
    "name": "Keen Machete",
    "level": 6,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_sword_16",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 3,
    "type": "weapon",
    "val": 37
  },
  "item_bladecunning": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "none",
    "id": "item_bladecunning",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 1
      }
    ],
    "effects": [],
    "dmgmax": 15,
    "name": "Blade of Cunning",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_weapon_shortblade_26",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 7,
    "type": "weapon",
    "val": 230
  },
  "item_smallegg": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_smallegg",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Small Egg",
    "level": 1,
    "droprate": 33,
    "clas": "default",
    "icon": "Inv_egg_01",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "trade",
    "val": 4
  },
  "item_raggedlboots": {
    "slots": 0,
    "quality": "common",
    "loc": "boots",
    "id": "item_raggedlboots",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Ragged Leather Boots",
    "level": 3,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_boots_06",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 17,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 12
  },
  "item_minorhealpot": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_minorhealpot",
    "mat": "none",
    "dropstackmax": 1,
    "abil": "abil_item_minorhealpot",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Minor Healing Potion",
    "level": 1,
    "droprate": 1,
    "clas": "default",
    "icon": "Inv_potion_49",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 60
  },
  "item_smalldagger": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_smalldagger",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 3,
    "name": "Small Dagger",
    "level": 3,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_weapon_shortblade_01",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 2,
    "type": "weapon",
    "val": 37
  },
  "item_ragepot": {
    "slots": 0,
    "quality": "common",
    "desc": "",
    "loc": "none",
    "armor": 0,
    "mat": "none",
    "abil": "abil_ragepotion",
    "stats": null,
    "effects": null,
    "id": "item_ragepot",
    "name": "Rage Potion",
    "level": 14,
    "droprate": 100,
    "stack": 20,
    "icon": "Inv_potion_24",
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "worlddrop": false,
    "clas": "barbarian",
    "dmgmin": 0,
    "type": "consumable",
    "val": 200
  },
  "item_gloamband": {
    "slots": 0,
    "quality": "rare",
    "loc": "ring",
    "id": "item_gloamband",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "sta",
        "num": 4
      },
      {
        "stat": "int",
        "num": 5
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Gloaming Band",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_jewelry_ring_34",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 1227
  },
  "item_papabag": {
    "slots": 20,
    "quality": "epic",
    "loc": "none",
    "id": "item_papabag",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Papa's New Bag",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_bag_26_spellfire",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "bag",
    "val": 8750
  },
  "item_tarnishedvleggings": {
    "slots": 0,
    "quality": "common",
    "loc": "legs",
    "id": "item_tarnishedvleggings",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Tarnished Chain Leggings",
    "level": 4,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_pants_03",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 47,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 420
  },
  "item_ruinedpelt": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_ruinedpelt",
    "mat": "none",
    "dropstackmax": 2,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Ruined Pelt",
    "level": 1,
    "droprate": 5,
    "clas": "default",
    "icon": "Inv_misc_pelt_wolf_ruin_04",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "trade",
    "val": 5
  },
  "item_bentstaff": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_bentstaff",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 2,
    "name": "Bent Staff",
    "level": 1,
    "droprate": 0,
    "clas": "default",
    "icon": "Inv_staff_08",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 1,
    "type": "weapon",
    "val": 4
  },
  "item_gizbocrest": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "trinket",
    "id": "item_gizbocrest",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "sta",
        "num": 3
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Crest of Courage",
    "level": 1,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_shield_05",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 500
  },
  "item_healherb": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_healherb",
    "mat": "none",
    "dropstackmax": 3,
    "abil": "abil_healherb",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Healing Herb",
    "level": 5,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_herb_01",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 10,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 2
  },
  "item_brillnecklace": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "neck",
    "id": "item_brillnecklace",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "str",
        "num": 2
      },
      {
        "stat": "agi",
        "num": 2
      },
      {
        "stat": "sta",
        "num": 1
      },
      {
        "stat": "int",
        "num": 2
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Brilliant Necklace",
    "level": 6,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_jewelry_necklace_01",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 750
  },
  "item_rustedcbracers": {
    "slots": 0,
    "quality": "common",
    "loc": "wrist",
    "id": "item_rustedcbracers",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Rusted Chain Bracers",
    "level": 3,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_bracer_05",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 23,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 28
  },
  "item_bardtrousers": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "legs",
    "id": "item_bardtrousers",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 2
      },
      {
        "stat": "sta",
        "num": 2
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Bard's Trousers",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_pants_06",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 71,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 525
  },
  "item_dirtylbelt": {
    "slots": 0,
    "quality": "common",
    "loc": "belt",
    "id": "item_dirtylbelt",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Dirty Leather Belt",
    "level": 3,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_belt_04",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 18,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 11
  },
  "item_primalcape": {
    "slots": 0,
    "quality": "common",
    "loc": "back",
    "id": "item_primalcape",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Primal Cape",
    "level": 9,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_cape_03",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 14,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 24
  },
  "item_staff_faith": {
    "slots": 0,
    "quality": "rare",
    "loc": "none",
    "id": "item_staff_faith",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "int",
        "num": 14
      },
      {
        "stat": "sta",
        "num": 8
      }
    ],
    "effects": [],
    "dmgmax": 5,
    "name": "Staff of Foresaken Faith",
    "level": 16,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_staff_29",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 2,
    "type": "weapon",
    "val": 1877
  },
  "item_boarleggings": {
    "slots": 0,
    "quality": "uncommon",
    "stack": 1,
    "loc": "legs",
    "armor": 58,
    "mat": "leather",
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 2
      },
      {
        "stat": "sta",
        "num": 3
      }
    ],
    "effects": [],
    "id": "item_boarleggings",
    "name": "Boarhide Leggings",
    "level": 8,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_pants_12",
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "worlddrop": false,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 300
  },
  "item_bandfstrength": {
    "slots": 0,
    "quality": "rare",
    "loc": "ring",
    "id": "item_bandfstrength",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "str",
        "num": 7
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Band of Foul Strength",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_jewelry_ring_08",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 820
  },
  "item_largeaxe": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_largeaxe",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 11,
    "name": "Large Axe",
    "level": 8,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_axe_10",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 6,
    "type": "weapon",
    "val": 96
  },
  "item_treebranch": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_treebranch",
    "mat": "none",
    "dropstackmax": 2,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Tree Branch",
    "level": 1,
    "droprate": 70,
    "clas": "default",
    "icon": "Trade_herbalism",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "quest",
    "val": 0
  },
  "item_ringprec": {
    "slots": 0,
    "quality": "rare",
    "desc": "",
    "icon": "Inv_jewelry_ring_14",
    "loc": "ring",
    "armor": 0,
    "mat": "none",
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 6
      }
    ],
    "effects": [
      {
        "value": "eff_ringprec"
      }
    ],
    "id": "item_ringprec",
    "name": "Ring of Precision",
    "level": 11,
    "droprate": 100,
    "stack": 1,
    "dmgmin": 0,
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "worlddrop": true,
    "clas": "default",
    "type": "armor",
    "val": 1807
  },
  "item_roastboar": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_roastboar",
    "mat": "none",
    "dropstackmax": 1,
    "abil": "abil_item_roastboar",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Roasted Boar Meat",
    "level": 1,
    "droprate": 0,
    "clas": "default",
    "icon": "Inv_misc_food_18",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 30
  },
  "item_springwater": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_springwater",
    "mat": "none",
    "dropstackmax": 1,
    "abil": "abil_item_springwater",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Refreshing Spring Water",
    "level": 1,
    "droprate": 3,
    "clas": "shaman",
    "icon": "Inv_drink_07",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 20
  },
  "item_finescim": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_finescim",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 7,
    "name": "Fine Scimitar",
    "level": 6,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_sword_24",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 3,
    "type": "weapon",
    "val": 37
  },
  "item_skullhatchet": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_skullhatchet",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 9,
    "name": "Skull Hatchet",
    "level": 8,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_axe_11",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 4,
    "type": "weapon",
    "val": 81
  },
  "item_rockmace": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_rockmace",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 6,
    "name": "Rock Mace",
    "level": 5,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_mace_07",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 2,
    "type": "weapon",
    "val": 24
  },
  "item_beatenbattleaxe": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_beatenbattleaxe",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 4,
    "name": "Beaten Battle Axe",
    "level": 1,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_throwingaxe_06",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 2,
    "type": "weapon",
    "val": 65
  },
  "item_lessermanapot": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_lessermanapot",
    "mat": "none",
    "dropstackmax": 1,
    "abil": "abil_lessermanapot",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Lesser Mana Potion",
    "level": 11,
    "droprate": 100,
    "clas": "shaman",
    "icon": "Inv_potion_71",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 300
  },
  "item_hulkcloak": {
    "slots": 0,
    "abil": null,
    "loc": "back",
    "armor": 29,
    "mat": "none",
    "clas": "default",
    "quality": "uncommon",
    "stats": [
      {
        "stat": "str",
        "num": 1
      },
      {
        "stat": "sta",
        "num": 3
      }
    ],
    "effects": [],
    "id": "item_hulkcloak",
    "name": "Hulking Cloak",
    "level": 13,
    "droprate": 100,
    "stack": 1,
    "icon": "Inv_misc_cape_20",
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "worlddrop": false,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 444
  },
  "item_crackedegg": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_crackedegg",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Cracked Egg Shells",
    "level": 1,
    "droprate": 2,
    "clas": "default",
    "icon": "Inv_egg_04",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "trade",
    "val": 4
  },
  "item_raidchestpiece": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "chest",
    "id": "item_raidchestpiece",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "str",
        "num": 4
      },
      {
        "stat": "sta",
        "num": 4
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Raider's Chestpiece",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_chest_chain_07",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 143,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 812
  },
  "item_kodobag": {
    "slots": 6,
    "quality": "common",
    "loc": "none",
    "id": "item_kodobag",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Kodo Hide Bag",
    "level": 5,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_bag_10",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "bag",
    "val": 850
  },
  "item_worndagger": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_worndagger",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 2,
    "name": "Worn Dagger",
    "level": 1,
    "droprate": 0,
    "clas": "default",
    "icon": "Inv_weapon_shortblade_05",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 1,
    "type": "weapon",
    "val": 3
  },
  "item_feralshoulders": {
    "slots": 0,
    "quality": "common",
    "loc": "shoulders",
    "id": "item_feralshoulders",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Feral Shoulder Pads",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_shoulder_08",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 63,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 62
  },
  "item_raidlegguards": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "legs",
    "id": "item_raidlegguards",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "sta",
        "num": 3
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Raider's Legguards",
    "level": 11,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_pants_03",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 120,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 742
  },
  "item_handlvest": {
    "slots": 0,
    "quality": "common",
    "loc": "chest",
    "id": "item_handlvest",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Handstitched Leather Vest",
    "level": 8,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_chest_wolf",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 43,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 40
  },
  "item_thistletea": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_thistletea",
    "mat": "none",
    "dropstackmax": 1,
    "abil": "abil_thistletea",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Thistle Tea",
    "level": 1,
    "droprate": 100,
    "clas": "scout",
    "icon": "Inv_drink_milk_05",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 10,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 200
  },
  "item_crackedlvest": {
    "slots": 0,
    "quality": "common",
    "loc": "chest",
    "id": "item_crackedlvest",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Cracked Leather Vest",
    "level": 4,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_shirt_06",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 33,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 550
  },
  "item_cheese": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_cheese",
    "mat": "none",
    "dropstackmax": 3,
    "abil": "abil_cheese",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Old Cheese",
    "level": 1,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_food_37",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 1
  },
  "item_tarnishedcvest": {
    "slots": 0,
    "quality": "common",
    "loc": "chest",
    "id": "item_tarnishedcvest",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Tarnished Chain Vest",
    "level": 4,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_chest_chain",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 53,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 600
  },
  "item_moonbag": {
    "slots": 16,
    "quality": "uncommon",
    "loc": "none",
    "id": "item_moonbag",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Mooncloth Bag",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_bag_14",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "bag",
    "val": 10000
  },
  "item_augcbelt": {
    "slots": 0,
    "quality": "common",
    "loc": "belt",
    "armor": 56,
    "mat": "mail",
    "clas": "default",
    "abil": null,
    "stats": [],
    "effects": [],
    "id": "item_augcbelt",
    "name": "Augmented Chain Belt",
    "level": 8,
    "droprate": 100,
    "stack": 1,
    "icon": "Inv_belt_03",
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "worlddrop": true,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 279
  },
  "item_gear": {
    "slots": 0,
    "abil": null,
    "loc": "none",
    "armor": 0,
    "mat": "none",
    "quality": "epic",
    "stats": null,
    "effects": null,
    "id": "item_gear",
    "name": "Schematic: Mech-Saw 9000",
    "level": 1,
    "droprate": 100,
    "stack": 20,
    "icon": "Inv_scroll_04",
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "type": "quest",
    "worlddrop": false,
    "desc": "",
    "clas": "default",
    "dmgmin": 0,
    "val": 0
  },
  "item_brandy": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_brandy",
    "mat": "none",
    "dropstackmax": 1,
    "abil": "abil_brandy",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Snowplum Brandy",
    "level": 11,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_drink_02",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 37
  },
  "item_kmmallet": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_kmmallet",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 9,
    "name": "Kobold Mining Mallet",
    "level": 7,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_hammer_09",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 4,
    "type": "weapon",
    "val": 58
  },
  "item_raidbracers": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "wrist",
    "id": "item_raidbracers",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "str",
        "num": 1
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Raider's Bracers",
    "level": 9,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_bracer_13",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 55,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 269
  },
  "item_bigone": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "armor": 0,
    "mat": "none",
    "abil": "abil_bigone",
    "stats": null,
    "effects": null,
    "id": "item_bigone",
    "name": "The Big One",
    "level": 1,
    "droprate": 100,
    "stack": 20,
    "icon": "Inv_misc_bomb_04",
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "dmgmin": 0,
    "worlddrop": false,
    "desc": "",
    "clas": "default",
    "type": "consumable",
    "val": 1000
  },
  "item_augcvest": {
    "slots": 0,
    "quality": "common",
    "loc": "chest",
    "id": "item_augcvest",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Augmented Chain Vest",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_chest_plate12",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 120,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 532
  },
  "item_goldnecklace": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "neck",
    "id": "item_goldnecklace",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Golden Necklace",
    "level": 1,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_jewelry_necklace_08",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 350
  },
  "item_warbringer": {
    "slots": 0,
    "quality": "epic",
    "loc": "none",
    "id": "item_warbringer",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "sta",
        "num": 12
      }
    ],
    "effects": [
      {
        "value": "eff_warbringer"
      }
    ],
    "dmgmax": 49,
    "name": "Warbringer",
    "level": 20,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_axe_10",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 23,
    "type": "weapon",
    "val": 65991
  },
  "item_crackedlpants": {
    "slots": 0,
    "quality": "common",
    "loc": "legs",
    "id": "item_crackedlpants",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Cracked Leather Pants",
    "level": 4,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_pants_10",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 29,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 330
  },
  "item_sblackjack": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_sblackjack",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 11,
    "name": "Studded Blackjack",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_mace_01",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 5,
    "type": "weapon",
    "val": 148
  },
  "item_thicknecklace": {
    "slots": 0,
    "abil": null,
    "loc": "neck",
    "armor": 0,
    "mat": "none",
    "quality": "uncommon",
    "stats": [
      {
        "stat": "sta",
        "num": 3
      }
    ],
    "effects": [],
    "id": "item_thicknecklace",
    "name": "Thick Bronze Necklace",
    "level": 17,
    "droprate": 100,
    "stack": 1,
    "icon": "Inv_belt_19",
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "dmgmin": 0,
    "worlddrop": false,
    "desc": "",
    "clas": "default",
    "type": "armor",
    "val": 750
  },
  "item_2sledge": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "none",
    "id": "item_2sledge",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "str",
        "num": 1
      },
      {
        "stat": "sta",
        "num": 1
      }
    ],
    "effects": [],
    "dmgmax": 20,
    "name": "2 Stone Sledgehammer",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_mace_02",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 10,
    "type": "weapon",
    "val": 409
  },
  "item_bardboots": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "boots",
    "id": "item_bardboots",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 2
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Bard's Boots",
    "level": 8,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_boots_05",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 51,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 320
  },
  "item_key": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_key",
    "mat": "none",
    "dropstackmax": 1,
    "abil": "abil_key",
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Skeleton Key",
    "level": 1,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_key_11",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 5,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 100
  },
  "item_linen": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_linen",
    "mat": "none",
    "dropstackmax": 2,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Linen Cloth",
    "level": 5,
    "droprate": 76,
    "clas": "default",
    "icon": "Inv_fabric_linen_01",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "trade",
    "val": 13
  },
  "item_tsatchel": {
    "slots": 6,
    "quality": "common",
    "loc": "none",
    "id": "item_tsatchel",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Toy Satchel",
    "level": 1,
    "droprate": 0,
    "clas": "default",
    "icon": "Inv_misc_bag_09_red",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "bag",
    "val": 250
  },
  "item_tribalgloves": {
    "slots": 0,
    "quality": "common",
    "loc": "gloves",
    "id": "item_tribalgloves",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Tribal Gloves",
    "level": 7,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_gauntlets_19",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 35,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 59
  },
  "item_cudgel": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_cudgel",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 7,
    "name": "Cudgel",
    "level": 7,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_torch_unlit",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 3,
    "type": "weapon",
    "val": 57
  },
  "item_bloodfring": {
    "slots": 0,
    "abil": null,
    "loc": "ring",
    "armor": 0,
    "mat": "none",
    "quality": "uncommon",
    "stats": [
      {
        "stat": "int",
        "num": 3
      }
    ],
    "effects": [],
    "id": "item_bloodfring",
    "name": "Bloodfeather Ring",
    "level": 20,
    "droprate": 100,
    "stack": 1,
    "icon": "Inv_jewelry_ring_36",
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "type": "armor",
    "worlddrop": false,
    "desc": "",
    "clas": "default",
    "dmgmin": 0,
    "val": 517
  },
  "item_copshortsword": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_copshortsword",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 11,
    "name": "Copper Shortsword",
    "level": 9,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_sword_26",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 5,
    "type": "weapon",
    "val": 110
  },
  "item_nubcloak": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "back",
    "id": "item_nubcloak",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 1
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Nubish Cloak",
    "level": 11,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_cape_14",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 18,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 97
  },
  "item_kodolegs": {
    "slots": 0,
    "quality": "common",
    "loc": "legs",
    "id": "item_kodolegs",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Rough-Hewn Kodo Leggings",
    "level": 9,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_pants_wolf",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 40,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 54
  },
  "item_rustcbelt": {
    "slots": 0,
    "quality": "common",
    "loc": "belt",
    "id": "item_rustcbelt",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Rusted Chain Belt",
    "level": 1,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_belt_06",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 30,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 7
  },
  "item_sbastsword": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "none",
    "id": "item_sbastsword",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 2
      }
    ],
    "effects": [],
    "dmgmax": 18,
    "name": "Steady Bastard Sword",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_sword_34",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 12,
    "type": "weapon",
    "val": 305
  },
  "item_wellusword": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_wellusword",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 12,
    "name": "Well-Used Sword",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_sword_04",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 6,
    "type": "weapon",
    "val": 144
  },
  "item_imsimplecape": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "back",
    "id": "item_imsimplecape",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "sta",
        "num": 1
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Imbued Simple Cape",
    "level": 11,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_cape_22",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 18,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 94
  },
  "item_raggedlgloves": {
    "slots": 0,
    "quality": "common",
    "loc": "gloves",
    "id": "item_raggedlgloves",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Ragged Leather Gloves",
    "level": 3,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_gauntlets_18",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 17,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 14
  },
  "item_grizzlybelt": {
    "slots": 0,
    "quality": "common",
    "loc": "belt",
    "id": "item_grizzlybelt",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Grizzly Belt",
    "level": 7,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_belt_09",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 34,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 47
  },
  "item_chippedbtusk": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_chippedbtusk",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Chipped Boar Tusk",
    "level": 1,
    "droprate": 10,
    "clas": "default",
    "icon": "Inv_misc_bone_04",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "trade",
    "val": 38
  },
  "item_augcbracers": {
    "slots": 0,
    "quality": "common",
    "loc": "wrist",
    "id": "item_augcbracers",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Augmented Chain Bracers",
    "level": 6,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_bracer_07",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 45,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 290
  },
  "item_bardbracers": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "wrist",
    "id": "item_bardbracers",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "sta",
        "num": 1
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Bard's Bracers",
    "level": 7,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_bracer_05",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 31,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 174
  },
  "item_drakehead": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "head",
    "id": "item_drakehead",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "int",
        "num": 9
      },
      {
        "stat": "sta",
        "num": 3
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Drakefire Headguard",
    "level": 12,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_helmet_17",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 121,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 915
  },
  "item_frayedcloak": {
    "slots": 0,
    "quality": "common",
    "loc": "back",
    "id": "item_frayedcloak",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Frayed Cloak",
    "level": 4,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_cape_10",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 10,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 7
  },
  "item_dustybag": {
    "slots": 6,
    "quality": "common",
    "loc": "none",
    "id": "item_dustybag",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Dusty Bag",
    "level": 5,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_misc_bag_09_red",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "bag",
    "val": 250
  },
  "item_huntbracers": {
    "slots": 0,
    "quality": "common",
    "loc": "wrist",
    "id": "item_huntbracers",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Huntsman's Bracers",
    "level": 7,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_bracer_08",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 17,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 13
  },
  "item_splinttusk": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_splinttusk",
    "mat": "none",
    "dropstackmax": 2,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Splintered Tusk",
    "level": 1,
    "droprate": 5,
    "clas": "default",
    "icon": "Inv_misc_bone_05",
    "dropstackmin": 1,
    "worlddrop": false,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "trade",
    "val": 6
  },
  "item_wornshortsword": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_wornshortsword",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 3,
    "name": "Worn Shortsword",
    "level": 1,
    "droprate": 0,
    "clas": "default",
    "icon": "Inv_sword_04",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 1,
    "type": "weapon",
    "val": 6
  },
  "item_primalboots": {
    "slots": 0,
    "quality": "common",
    "loc": "boots",
    "id": "item_primalboots",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Primal Boots",
    "level": 9,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_boots_08",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 32,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 42
  },
  "item_reinforcedlcap": {
    "slots": 0,
    "quality": "common",
    "loc": "head",
    "id": "item_reinforcedlcap",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "Reinforced Leather Cap",
    "level": 11,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_helmet_15",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 70,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 74
  },
  "item_shellcracker": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_shellcracker",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 16,
    "name": "The Shell Cracker",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_mace_33",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 12,
    "type": "weapon",
    "val": 172
  },
  "item_bardgloves": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "gloves",
    "id": "item_bardgloves",
    "mat": "leather",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "agi",
        "num": 2
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Bard's Gloves",
    "level": 9,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_gauntlets_15",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 48,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 229
  },
  "item_raidboots": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "boots",
    "id": "item_raidboots",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "str",
        "num": 1
      },
      {
        "stat": "sta",
        "num": 1
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Raider's Boots",
    "level": 11,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_boots_01",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 94,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 533
  },
  "item_arcanebomb": {
    "slots": 0,
    "quality": "common",
    "stack": 20,
    "loc": "none",
    "armor": 0,
    "mat": "none",
    "abil": "abil_arcanebomb",
    "stats": null,
    "effects": null,
    "id": "item_arcanebomb",
    "name": "Arcane Bomb",
    "level": 1,
    "droprate": 100,
    "clas": "default",
    "icon": "Spell_shadow_mindbomb",
    "dropstackmin": 1,
    "dmgmax": 0,
    "dropstackmax": 1,
    "worlddrop": false,
    "desc": "",
    "dmgmin": 0,
    "type": "consumable",
    "val": 200
  },
  "item_malachite": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "none",
    "id": "item_malachite",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": null,
    "effects": null,
    "dmgmax": 0,
    "name": "Malachite",
    "level": 1,
    "droprate": 2,
    "clas": "default",
    "icon": "Inv_misc_gem_emerald_03",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 20,
    "desc": "",
    "dmgmin": 0,
    "type": "trade",
    "val": 50
  },
  "item_warpshoulder": {
    "slots": 0,
    "quality": "common",
    "loc": "shoulders",
    "id": "item_warpshoulder",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 0,
    "name": "War Paint Shoulder Pads",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_shoulder_07",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 110,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 385
  },
  "item_arcanestaff": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "none",
    "id": "item_arcanestaff",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "int",
        "num": 1
      }
    ],
    "effects": [],
    "dmgmax": 13,
    "name": "Arcane Staff",
    "level": 10,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_staff_10",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 6,
    "type": "weapon",
    "val": 306
  },
  "item_chippedquarterstaff": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_chippedquarterstaff",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 3,
    "name": "Chipped Quarterstaff",
    "level": 1,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_staff_08",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 1,
    "type": "weapon",
    "val": 45
  },
  "item_crudebattleaxe": {
    "slots": 0,
    "quality": "common",
    "loc": "none",
    "id": "item_crudebattleaxe",
    "mat": "none",
    "dropstackmax": 1,
    "abil": null,
    "stats": [],
    "effects": [],
    "dmgmax": 4,
    "name": "Crude Battle Axe",
    "level": 2,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_throwingaxe_05",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 0,
    "stack": 1,
    "desc": "",
    "dmgmin": 1,
    "type": "weapon",
    "val": 29
  },
  "item_bloodtboots": {
    "slots": 0,
    "quality": "uncommon",
    "loc": "boots",
    "id": "item_bloodtboots",
    "mat": "mail",
    "dropstackmax": 1,
    "abil": null,
    "stats": [
      {
        "stat": "sta",
        "num": 2
      },
      {
        "stat": "int",
        "num": 2
      }
    ],
    "effects": [],
    "dmgmax": 0,
    "name": "Bloodtaint Boots",
    "level": 9,
    "droprate": 100,
    "clas": "default",
    "icon": "Inv_boots_chain_03",
    "dropstackmin": 1,
    "worlddrop": true,
    "armor": 84,
    "stack": 1,
    "desc": "",
    "dmgmin": 0,
    "type": "armor",
    "val": 614
  }
}`;