        const questDBJSON = `        {
            "quest_arena1": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": [],
                "id": "quest_arena1",
                "pre_items": [],
                "submit": "npc_halfbreed",
                "rew_items": [],
                "summary": "Defeat your next challenge inside the Arena and return to Harry Halfbreed.",
                "pre_level": 0,
                "giver": "npc_halfbreed",
                "name": "Challenge 1",
                "pre_class": "none",
                "dinc": "dia_arena_inc",
                "rew_xp": 100,
                "dcom": "dia_arena_com",
                "rew_copper": 0,
                "dnew": "dia_arena1",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["kill", "mon_super_boar", 1]
                ]
            },
            "quest_arena8": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": ["quest_arena7"],
                "id": "quest_arena8",
                "pre_items": [],
                "submit": "npc_halfbreed",
                "rew_items": [],
                "summary": "Defeat your next challenge inside the Arena and return to Harry Halfbreed.",
                "pre_level": 0,
                "giver": "npc_halfbreed",
                "name": "Challenge 8",
                "pre_class": "none",
                "dinc": "dia_arena_df",
                "rew_xp": 500,
                "dcom": "dia_arena_final",
                "rew_copper": 0,
                "dnew": "dia_arena8",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["kill", "mon_doom_frog", 1]
                ]
            },
            "quest_bombs": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": [],
                "id": "quest_bombs",
                "pre_items": [],
                "submit": "npc_bombs",
                "rew_items": [],
                "summary": "Zurgul wants you to collect 5 piles of manure from the boars to the east.",
                "pre_level": 0,
                "giver": "npc_bombs",
                "name": "Stinky Proposition",
                "pre_class": "none",
                "dinc": "dia_bombs_inc",
                "rew_xp": 100,
                "dcom": "dia_bombs_com",
                "rew_copper": 0,
                "dnew": "dia_bombs_new",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["item", "item_manure", 5]
                ]
            },
            "quest_nightwatch": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": ["quest_gizbo_armor", "quest_gizbo_goods"],
                "id": "quest_nightwatch",
                "pre_items": [],
                "submit": "npc_guard1",
                "rew_items": [
                    ["item_gizbocrest", 1]
                ],
                "summary": "Talk to Slen in Camp Gizbo when you are ready to face the quillboar attack.",
                "pre_level": 0,
                "giver": "npc_guard1",
                "dnew": "dia_nightwatch_new",
                "pre_class": "none",
                "dinc": "dia_none",
                "rew_xp": 300,
                "dcom": "dia_nightwatch",
                "rew_copper": 0,
                "name": "Quillboar Attack",
                "drinc": "",
                "drcom": "",
                "objec": []
            },
            "quest_003": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": ["quest_quillboar_camp"],
                "id": "quest_003",
                "pre_items": [],
                "submit": "npc_mad_gomsil",
                "rew_items": [],
                "summary": "Chief Gizbo wants you to talk to the Gomsil the engineer who might be able to locate the assassin you seek. The engineer is hiding in his observatory, east of Red Cloud Mesa. ",
                "pre_level": 0,
                "giver": "npc_chief_gizbo2",
                "name": "Queer Engineer",
                "pre_class": "none",
                "dinc": "dia_q003_inc",
                "rew_xp": 50,
                "dcom": "dia_none",
                "rew_copper": 0,
                "dnew": "dia_none",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["item", "item_gear", 1]
                ]
            },
            "quest_quillboar_camp": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": [],
                "id": "quest_quillboar_camp",
                "pre_items": [],
                "submit": "npc_none",
                "rew_items": [],
                "summary": "Chief Gizbo wants you to head to the quillboar camp and defeat Earthcaller Thorntusk. Talk to Slen to the west of the camp to depart.",
                "pre_level": 0,
                "giver": "npc_chief_gizbo2",
                "dnew": "dia_quillboar_camp_new",
                "pre_class": "none",
                "dinc": "dia_quillboar_camp_inc",
                "rew_xp": 0,
                "dcom": "dia_none",
                "rew_copper": 0,
                "name": "Best Defense",
                "drinc": "",
                "drcom": "",
                "objec": []
            },
            "quest_002": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": [],
                "id": "quest_002",
                "pre_items": [],
                "submit": "npc_chief_none",
                "rew_items": [],
                "summary": "Chief Gizbo wants you to help around the camp. Look for villagers who might need your aid. Return to Chief Gizbo when you have completed all tasks.",
                "pre_level": 0,
                "giver": "npc_chief_gizbo1",
                "dnew": "dia_q002_new",
                "pre_class": "none",
                "dinc": "dia_q002_inc",
                "rew_xp": 100,
                "dcom": "dia_none",
                "rew_copper": 0,
                "name": "Rebuilding Camp Gizbo",
                "drinc": "",
                "drcom": "",
                "objec": []
            },
            "quest_001": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": [],
                "id": "quest_001",
                "pre_items": [],
                "submit": "npc_guard1",
                "rew_items": [],
                "summary": "Venture through Mulgore to find the murloc camp.",
                "pre_level": 0,
                "giver": "new_game",
                "dnew": "dia_start",
                "pre_class": "none",
                "dinc": "dia_start",
                "rew_xp": 100,
                "dcom": "dia_1_2",
                "rew_copper": 0,
                "name": "Find Camp Gizbo",
                "drinc": "",
                "drcom": "",
                "objec": []
            },
            "quest_best_defense2": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": [],
                "id": "quest_best_defense2",
                "pre_items": [],
                "submit": "npc_chief_gizbo2",
                "rew_items": [
                    ["item_gear", 1]
                ],
                "summary": "Return to Chief Gizbo and inform him of the defeated Earthcaller.",
                "pre_level": 0,
                "giver": "npc_none",
                "dnew": "dia_none",
                "pre_class": "none",
                "dinc": "dia_none",
                "rew_xp": 300,
                "dcom": "dia_quillboar_camp_com",
                "rew_copper": 0,
                "name": "Return to Chief Gizbo",
                "drinc": "",
                "drcom": "",
                "objec": []
            },
            "quest_gizbo_alch": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": ["quest_gizbo_armor", "quest_gizbo_goods"],
                "id": "quest_gizbo_alch",
                "pre_items": [],
                "submit": "npc_gizbo_alch",
                "rew_items": [
                    ["item_minorhealpot", 1]
                ],
                "summary": "Arkin wants you to collect 10 vials of blood from any creature you can find.",
                "pre_level": 0,
                "giver": "npc_gizbo_alch",
                "dnew": "dia_q_gizbo_alch_new",
                "pre_class": "none",
                "dinc": "dia_q_gizbo_alch_inc",
                "rew_xp": 100,
                "dcom": "dia_q_gizbo_alch_com",
                "rew_copper": 0,
                "name": "Bloody Mess",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["item", "item_bloodvial", 10]
                ]
            },
            "quest_arena2": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": ["quest_arena1"],
                "id": "quest_arena2",
                "pre_items": [],
                "submit": "npc_halfbreed",
                "rew_items": [],
                "summary": "Defeat your next challenge inside the Arena and return to Harry Halfbreed.",
                "pre_level": 0,
                "giver": "npc_halfbreed",
                "name": "Challenge 2",
                "pre_class": "none",
                "dinc": "dia_arena_inc",
                "rew_xp": 100,
                "dcom": "dia_arena_com",
                "rew_copper": 0,
                "dnew": "dia_arena2",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["kill", "mon_vulture", 1]
                ]
            },
            "quest_arena3": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": ["quest_arena2"],
                "id": "quest_arena3",
                "pre_items": [],
                "submit": "npc_halfbreed",
                "rew_items": [],
                "summary": "Defeat your next challenge inside the Arena and return to Harry Halfbreed.",
                "pre_level": 0,
                "giver": "npc_halfbreed",
                "name": "Challenge 3",
                "pre_class": "none",
                "dinc": "dia_arena_inc",
                "rew_xp": 100,
                "dcom": "dia_arena_com",
                "rew_copper": 0,
                "dnew": "dia_arena3",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["kill", "mon_hellboar", 1]
                ]
            },
            "quest_save_gurgul": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": [],
                "id": "quest_save_gurgul",
                "pre_items": [],
                "submit": "npc_none",
                "rew_items": [],
                "summary": "This is a placeholder.",
                "pre_level": 0,
                "giver": "npc_gurgul_qb",
                "dnew": "dia_save_gurgul",
                "pre_class": "none",
                "dinc": "dia_none",
                "rew_xp": 100,
                "dcom": "dia_none",
                "rew_copper": 0,
                "name": "Save Gurgul",
                "drinc": "",
                "drcom": "",
                "objec": []
            },
            "quest_arena4": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": ["quest_arena3"],
                "id": "quest_arena4",
                "pre_items": [],
                "submit": "npc_halfbreed",
                "rew_items": [],
                "summary": "Defeat your next challenge inside the Arena and return to Harry Halfbreed.",
                "pre_level": 0,
                "giver": "npc_halfbreed",
                "name": "Challenge 4",
                "pre_class": "none",
                "dinc": "dia_arena_inc",
                "rew_xp": 100,
                "dcom": "dia_arena_com",
                "rew_copper": 0,
                "dnew": "dia_arena4",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["kill", "mon_thorntusk2", 1]
                ]
            },
            "quest_gizbo_armor": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": [],
                "id": "quest_gizbo_armor",
                "pre_items": [],
                "submit": "npc_gizbo_armor",
                "rew_items": [],
                "summary": "Jekel wants you to collect 6 tree branches from the carrion birds in Red Cloud Mesa.",
                "pre_level": 0,
                "giver": "npc_gizbo_armor",
                "dnew": "dia_q_gizbo_armor_new",
                "pre_class": "none",
                "dinc": "dia_q_gizbo_armor_inc",
                "rew_xp": 100,
                "dcom": "dia_q_gizbo_armor_com",
                "rew_copper": 0,
                "name": "Strong Foundation",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["item", "item_treebranch", 6]
                ]
            },
            "quest_arena6": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": ["quest_arena5"],
                "id": "quest_arena6",
                "pre_items": [],
                "submit": "npc_halfbreed",
                "rew_items": [],
                "summary": "Defeat your next challenge inside the Arena and return to Harry Halfbreed.",
                "pre_level": 0,
                "giver": "npc_halfbreed",
                "name": "Challenge 6",
                "pre_class": "none",
                "dinc": "dia_arena_inc",
                "rew_xp": 100,
                "dcom": "dia_arena_com",
                "rew_copper": 0,
                "dnew": "dia_arena6",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["kill", "mon_murloc_sham", 1]
                ]
            },
            "quest_gizbo_goods": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": [],
                "id": "quest_gizbo_goods",
                "pre_items": [],
                "submit": "npc_gizbo_goods",
                "rew_items": [],
                "summary": "Dinga wants you to collect 18 chunks of meat from the boars in Mulgore.",
                "pre_level": 0,
                "giver": "npc_gizbo_goods",
                "dnew": "dia_q_gizbo_goods",
                "pre_class": "none",
                "dinc": "dia_iq_gizbo_goods",
                "rew_xp": 100,
                "dcom": "dia_cq_gizbo_goods",
                "rew_copper": 0,
                "name": "Boar Meat",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["item", "item_q_chunkboar", 18]
                ]
            },
            "quest_arena7": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": ["quest_arena6"],
                "id": "quest_arena7",
                "pre_items": [],
                "submit": "npc_halfbreed",
                "rew_items": [],
                "summary": "Defeat your next challenge inside the Arena and return to Harry Halfbreed.",
                "pre_level": 0,
                "giver": "npc_halfbreed",
                "name": "Challenge 7",
                "pre_class": "none",
                "dinc": "dia_arena_inc",
                "rew_xp": 100,
                "dcom": "dia_arena_com",
                "rew_copper": 0,
                "dnew": "dia_arena7",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["kill", "mon_murloc_scout", 1]
                ]
            },
            "quest_arena5": {
                "repeat": false,
                "quest_items": [],
                "pre_quests": ["quest_arena4"],
                "id": "quest_arena5",
                "pre_items": [],
                "submit": "npc_halfbreed",
                "rew_items": [],
                "summary": "Defeat your next challenge inside the Arena and return to Harry Halfbreed.",
                "pre_level": 0,
                "giver": "npc_halfbreed",
                "name": "Challenge 5",
                "pre_class": "none",
                "dinc": "dia_arena_inc",
                "rew_xp": 100,
                "dcom": "dia_arena_com",
                "rew_copper": 0,
                "dnew": "dia_arena5",
                "drinc": "",
                "drcom": "",
                "objec": [
                    ["kill", "mon_murloc_barb", 1]
                ]
            }
        }`;