export const abilityDBJSON = `{
  "abil_milk": {
    "_event": "none",
    "sfx": "drink",
    "icon": "none",
    "cooldown": 0,
    "id": "abil_milk",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": 0,
    "effects": [],
    "name": "Ice Cold Milk",
    "cost": 100,
    "incombat": false,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 0,
    "scooldown": "food",
    "desc": "Restores $powmod Mana.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 0
  },
  "abil_healherb": {
    "_event": "none",
    "sfx": "food",
    "icon": "none",
    "cooldown": 0,
    "id": "abil_healherb",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Healing Herb",
    "cost": 0,
    "incombat": false,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 60,
    "scooldown": "food",
    "desc": "Restores $hpmod health.",
    "hpmodmax": 60,
    "type": "skill",
    "val": 0
  },
  "abil_item_springwater": {
    "_event": "none",
    "sfx": "drink",
    "icon": "none",
    "cooldown": 2,
    "id": "abil_item_springwater",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": 0,
    "effects": [],
    "name": "Refreshing Spring Water",
    "cost": 150,
    "incombat": false,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 0,
    "scooldown": "food",
    "desc": "Restores $powmod Mana. ($cooldown round cooldown)",
    "hpmodmax": 0,
    "type": "skill",
    "val": 0
  },
  "abil_enragedregen": {
    "hpmod_p": true,
    "sfx": "enragedregen",
    "desc": "$powmod Rage<br>$cooldown round cooldown<br>Restores 50% of base health and an addtional 500 health over 10 rounds.",
    "cooldown": 60,
    "id": "abil_enragedregen",
    "_event": "none",
    "animation": "idle",
    "target": "self",
    "clas": "barbarian",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_enragedregen"
      }
    ],
    "name": "Enraged Regeneration",
    "level": 33,
    "incombat": true,
    "icon": "Ability_warrior_focusedrage",
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "cost": -50,
    "hpmodmin": 50,
    "scooldown": "none",
    "cost_p": false,
    "hpmodmax": 50,
    "type": "skill",
    "val": 330
  },
  "abil_shredder_carve": {
    "_event": "none",
    "sfx": "none",
    "icon": "none",
    "cooldown": 0,
    "id": "abil_shredder_carve",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Carve",
    "cost": 0,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 1,
    "hpmodmin": -3,
    "scooldown": "none",
    "desc": "",
    "hpmodmax": -4,
    "type": "skill",
    "val": 0
  },
  "abil_mon_hex": {
    "hpmod_p": false,
    "sfx": "hex",
    "cost_p": false,
    "cooldown": 10,
    "id": "abil_mon_hex",
    "_event": "none",
    "animation": "default",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_mon_hex"
      }
    ],
    "name": "Hex",
    "level": 1,
    "incombat": true,
    "icon": "none",
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "cost": 0,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "",
    "hpmodmax": 0,
    "type": "spell",
    "val": 0
  },
  "abil_mon_lightbolt": {
    "_event": "none",
    "sfx": "lightbolt",
    "icon": "none",
    "cooldown": 0,
    "id": "abil_mon_lightbolt",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Lightning Bolt",
    "cost": 0,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 1,
    "hpmodmin": -14,
    "scooldown": "none",
    "desc": "",
    "hpmodmax": -14,
    "type": "spell",
    "val": 0
  },
  "abil_frog_doom": {
    "hpmod_p": true,
    "sfx": "none",
    "desc": "",
    "cooldown": 3,
    "id": "abil_frog_doom",
    "_event": "none",
    "animation": "idle",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Doom",
    "level": 1,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "cost": 0,
    "hpmodmin": -999999,
    "scooldown": "none",
    "icon": "none",
    "hpmodmax": -999999,
    "type": "spell",
    "val": 0
  },
  "abil_lessermanapot": {
    "hpmod_p": false,
    "sfx": "potion",
    "icon": "none",
    "cooldown": 6,
    "id": "abil_lessermanapot",
    "_event": "none",
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": -1,
    "effects": [],
    "name": "Lesser Mana Potion",
    "level": 1,
    "incombat": true,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "cost": 250,
    "hpmodmin": 0,
    "scooldown": "potion",
    "desc": "Instantly restores $powmod Mana. ($cooldown round cooldown)",
    "hpmodmax": 0,
    "type": "skill",
    "val": 0
  },
  "abil_execute": {
    "_event": "execute",
    "sfx": "execute",
    "icon": "Inv_sword_48",
    "cooldown": 0,
    "id": "abil_execute",
    "hpmod_p": false,
    "animation": "attackjump",
    "target": "enemy",
    "clas": "barbarian",
    "casttime": 0,
    "effects": [],
    "name": "Execute",
    "cost": 0,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 27,
    "hpmodmin": -50,
    "scooldown": "none",
    "desc": "100% of available Rage<br>Execute the target for $hpmod damage and an additional 5 damage for every point of rage. Target health must be at 30% or less.",
    "hpmodmax": -70,
    "type": "skill",
    "val": 270
  },
  "abil_berserkrage": {
    "_event": "none",
    "sfx": "berserkrage",
    "icon": "Spell_nature_ancestralguardian",
    "cooldown": 30,
    "id": "abil_berserkrage",
    "hpmod_p": false,
    "animation": "idle",
    "target": "self",
    "clas": "barbarian",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_berserkrage"
      }
    ],
    "name": "Berserker Rage",
    "cost": 5,
    "incombat": true,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 24,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$cooldown round cooldown<br>Generates $powmod rage and an additional 50 rage over 5 rounds.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 240
  },
  "abil_thistletea": {
    "_event": "none",
    "sfx": "drink",
    "icon": "none",
    "cooldown": 240,
    "id": "abil_thistletea",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": -1,
    "effects": [],
    "name": "Thistle Tea",
    "cost": 100,
    "incombat": true,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "Instantly restores 100 Energy. ($cooldown round cooldown)",
    "hpmodmax": 0,
    "type": "skill",
    "val": 0
  },
  "abil_evasion": {
    "_event": "none",
    "sfx": "evasion",
    "icon": "Spell_shadow_shadowward",
    "cooldown": 60,
    "id": "abil_evasion",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "scout",
    "casttime": -1,
    "effects": [
      {
        "value": "eff_evasion"
      }
    ],
    "name": "Evasion",
    "cost": 0,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 21,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$cooldown round cooldown<br>Instantly increases the Scout's dodge chance by 50% for 8 rounds.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 210
  },
  "abil_elemshield": {
    "_event": "none",
    "sfx": "elemshield",
    "icon": "Spell_nature_lightningshield",
    "cooldown": 240,
    "id": "abil_elemshield",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": -1,
    "effects": [
      {
        "value": "eff_elemshield"
      }
    ],
    "name": "Elemental Shield",
    "cost": -2,
    "incombat": true,
    "cost_p": true,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 6,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$cooldown round cooldown<br>Instantly increases stamina and intelligence by 10 for 240 rounds.",
    "hpmodmax": 0,
    "type": "spell",
    "val": 60
  },
  "abil_ancspirit": {
    "_event": "none",
    "sfx": "spirit",
    "icon": "Spell_nature_regenerate",
    "cooldown": 300,
    "id": "abil_ancspirit",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_ancspirit"
      }
    ],
    "name": "Ancestral Spirit",
    "cost": -100,
    "incombat": true,
    "cost_p": true,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 33,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$cooldown round cooldown<br>Protects the Shaman with an ancestral spirit that will instantly revive the Shaman with 100% of base health upon death. Lasts for 300 rounds.",
    "hpmodmax": 0,
    "type": "spell",
    "val": 330
  },
  "abil_healwave": {
    "_event": "none",
    "sfx": "heal",
    "icon": "Spell_nature_magicimmunity",
    "cooldown": 5,
    "id": "abil_healwave",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": -1,
    "effects": [
      {
        "value": "eff_healwave"
      }
    ],
    "name": "Healing Wave",
    "cost": -20,
    "incombat": true,
    "cost_p": true,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 3,
    "hpmodmin": 20,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$cooldown round cooldown<br>Instantly restores $hpmod health and an additional 50 health over 5 rounds.",
    "hpmodmax": 30,
    "type": "spell",
    "val": 30
  },
  "abil_slash": {
    "_event": "none",
    "sfx": "none",
    "icon": "none",
    "cooldown": 2,
    "id": "abil_slash",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_infectedwound"
      }
    ],
    "name": "Slash",
    "cost": 0,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 1,
    "hpmodmin": -7,
    "scooldown": "none",
    "desc": "Enemy attack",
    "hpmodmax": -10,
    "type": "skill",
    "val": 0
  },
  "abil_ragepotion": {
    "_event": "none",
    "sfx": "potion",
    "icon": "none",
    "cooldown": 60,
    "id": "abil_ragepotion",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": -1,
    "effects": [],
    "name": "Rage Potion",
    "cost": 40,
    "incombat": true,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "Instantly generates $powmod Rage. ($cooldown round cooldown)",
    "hpmodmax": 0,
    "type": "skill",
    "val": 0
  },
  "abil_ambush": {
    "_event": "none",
    "sfx": "ambush",
    "icon": "Ability_rogue_ambush",
    "cooldown": 3,
    "id": "abil_ambush",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "scout",
    "casttime": 0,
    "effects": [],
    "name": "Ambush",
    "cost": -60,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 30,
    "hpmodmin": -65,
    "scooldown": "none",
    "desc": "$powmod Energy<br>$cooldown round cooldown<br>An attack that deals $hpmod damage.",
    "hpmodmax": -100,
    "type": "skill",
    "val": 300
  },
  "abil_frostshock": {
    "_event": "none",
    "sfx": "frostshock",
    "icon": "Spell_frost_frostshock",
    "cooldown": 6,
    "id": "abil_frostshock",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "shaman",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_frostshock"
      }
    ],
    "name": "Frost Shock",
    "cost": -18,
    "incombat": true,
    "cost_p": true,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 24,
    "hpmodmin": -30,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$cooldown round cooldown<br>Shocks the target with frost, causing $hpmod damage and stunning it for the next round.",
    "hpmodmax": -35,
    "type": "spell",
    "val": 240
  },
  "abil_coldblood": {
    "hpmod_p": false,
    "sfx": "coldblood",
    "icon": "Spell_ice_lament",
    "cooldown": 45,
    "id": "abil_coldblood",
    "_event": "none",
    "animation": "default",
    "target": "self",
    "clas": "scout",
    "casttime": -1,
    "effects": [
      {
        "value": "eff_coldblood"
      }
    ],
    "name": "Cold Blood",
    "level": 15,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "cost": -25,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod Energy<br>$cooldown round cooldown<br>Increases the critical strike chance of melee attacks by 100% for the current round.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 150
  },
  "abil_item_minormanapot": {
    "hpmod_p": false,
    "sfx": "potion",
    "cost_p": false,
    "cooldown": 6,
    "id": "abil_item_minormanapot",
    "_event": "none",
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": -1,
    "effects": [],
    "name": "Minor Mana Potion",
    "level": 1,
    "incombat": true,
    "icon": "none",
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "cost": 150,
    "hpmodmin": 0,
    "scooldown": "potion",
    "desc": "Instantly restores $powmod Mana. ($cooldown round cooldown)",
    "hpmodmax": 0,
    "type": "skill",
    "val": 0
  },
  "abil_sinstrike": {
    "_event": "none",
    "sfx": "sinstrike",
    "icon": "Spell_shadow_ritualofsacrifice",
    "cooldown": 0,
    "id": "abil_sinstrike",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "scout",
    "casttime": 0,
    "effects": [],
    "name": "Sinister Strike",
    "cost": -45,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 1,
    "hpmodmin": -20,
    "scooldown": "none",
    "desc": "$powmod Energy<br>An attack that deals $hpmod damage.",
    "hpmodmax": -30,
    "type": "skill",
    "val": 0
  },
  "abil_recuperate": {
    "_event": "none",
    "sfx": "recuperate",
    "icon": "Ability_rogue_recuperate",
    "cooldown": 120,
    "id": "abil_recuperate",
    "hpmod_p": true,
    "animation": "default",
    "target": "self",
    "clas": "scout",
    "casttime": -1,
    "effects": [
      {
        "value": "eff_recuperate"
      }
    ],
    "name": "Recuperate",
    "cost": -30,
    "incombat": true,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 24,
    "hpmodmin": 20,
    "scooldown": "none",
    "desc": "$powmod Energy<br>$cooldown round cooldown<br>Instantly restores 20% of base health and an additional 300 health over 6 rounds.",
    "hpmodmax": 20,
    "type": "skill",
    "val": 240
  },
  "abil_slicedice": {
    "_event": "none",
    "sfx": "slicedice",
    "icon": "Ability_rogue_slicedice",
    "cooldown": 240,
    "id": "abil_slicedice",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "scout",
    "casttime": -1,
    "effects": [
      {
        "value": "eff_slicedice"
      }
    ],
    "name": "Slice and Dice",
    "cost": -25,
    "incombat": true,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 3,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod Energy<br>$cooldown round cooldown<br>Instantly enters a focused state, increasing agility by 20 for 240 rounds.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 30
  },
  "abil_carrion_bite": {
    "_event": "none",
    "sfx": "none",
    "icon": "none",
    "cooldown": 0,
    "id": "abil_carrion_bite",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Swoop",
    "cost": 0,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 1,
    "hpmodmin": -2,
    "scooldown": "none",
    "desc": "",
    "hpmodmax": -4,
    "type": "skill",
    "val": 0
  },
  "abil_item_minorhealpot": {
    "hpmod_p": false,
    "sfx": "potion",
    "desc": "Instantly restores $hpmod health. ($cooldown round cooldown)",
    "cooldown": 6,
    "id": "abil_item_minorhealpot",
    "_event": "none",
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": -1,
    "effects": [],
    "name": "Minor Healing Potion",
    "level": 1,
    "incombat": true,
    "icon": "none",
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "cost": 0,
    "hpmodmin": 100,
    "scooldown": "potion",
    "cost_p": false,
    "hpmodmax": 100,
    "type": "skill",
    "val": 0
  },
  "abil_flashbomb": {
    "hpmod_p": false,
    "sfx": "explosion",
    "icon": "none",
    "cooldown": 10,
    "id": "abil_flashbomb",
    "_event": "none",
    "animation": "unarmed",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_flashbomb"
      }
    ],
    "name": "Flash Bomb",
    "level": 1,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "cost": 0,
    "hpmodmin": -1,
    "scooldown": "bomb",
    "desc": "Inflicts $hpmod damage and stuns the target for 2 rounds. ($cooldown round cooldown)",
    "hpmodmax": -5,
    "type": "skill",
    "val": 0
  },
  "abil_lightbolt": {
    "_event": "none",
    "sfx": "lightbolt",
    "icon": "Spell_nature_lightning",
    "cooldown": 0,
    "id": "abil_lightbolt",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "shaman",
    "casttime": 0,
    "effects": [],
    "name": "Lightning Bolt",
    "cost": -8,
    "incombat": true,
    "cost_p": true,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 1,
    "hpmodmin": -14,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>Casts a bolt of lightning at the target for $hpmod damage.",
    "hpmodmax": -14,
    "type": "spell",
    "val": 0
  },
  "abil_kidneyshot": {
    "_event": "none",
    "sfx": "kidneyshot",
    "icon": "Ability_rogue_kidneyshot",
    "cooldown": 6,
    "id": "abil_kidneyshot",
    "hpmod_p": false,
    "animation": "unarmed",
    "target": "enemy",
    "clas": "scout",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_kidneyshot"
      }
    ],
    "name": "Kidney Shot",
    "cost": -25,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 33,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod Energy<br>$cooldown round cooldown<br>Stuns the target for 3 rounds.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 330
  },
  "abil_shieldwall": {
    "_event": "none",
    "sfx": "shieldwall",
    "icon": "Ability_warrior_shieldwall",
    "cooldown": 480,
    "id": "abil_shieldwall",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "barbarian",
    "casttime": -1,
    "effects": [
      {
        "value": "eff_shieldwall"
      }
    ],
    "name": "Shield Wall",
    "cost": -5,
    "incombat": true,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 18,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod Rage<br>$cooldown round cooldown<br>Instantly increases stamina by 30 for 480 rounds.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 180
  },
  "abil_frog_stare": {
    "_event": "none",
    "sfx": "none",
    "desc": "",
    "cooldown": 0,
    "id": "abil_frog_stare",
    "hpmod_p": false,
    "animation": "idle",
    "target": "self",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Vacant Stare",
    "level": 1,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "cost": 0,
    "hpmodmin": 0,
    "scooldown": "none",
    "icon": "none",
    "hpmodmax": 0,
    "type": "skill",
    "val": 0
  },
  "abil_garrote": {
    "_event": "none",
    "sfx": "garrote",
    "icon": "Ability_rogue_garrote",
    "cooldown": 20,
    "id": "abil_garrote",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "scout",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_garrote"
      }
    ],
    "name": "Garrote",
    "cost": -45,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "level": 27,
    "hpmodmin": -50,
    "scooldown": "none",
    "desc": "$powmod Energy<br>$cooldown round cooldown<br>Garrote the enemy, dealing $hpmod damage and an additional 1000 damage over 20 rounds.",
    "hpmodmax": -50,
    "type": "skill",
    "val": 270
  },
  "abil_kick": {
    "_event": "none",
    "sfx": "suckerpunch",
    "icon": "Inv_gauntlets_21",
    "cooldown": 6,
    "id": "abil_kick",
    "hpmod_p": false,
    "animation": "unarmed",
    "target": "enemy",
    "clas": "scout",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_kick"
      }
    ],
    "name": "Sucker Punch",
    "cost": -15,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "level": 6,
    "hpmodmin": -5,
    "scooldown": "none",
    "desc": "$powmod Energy<br>$cooldown round cooldown<br>A quick punch that deals 5 damage, interrupts spellcasting and silences the target for 4 rounds.",
    "hpmodmax": -5,
    "type": "skill",
    "val": 60
  },
  "abil_pickpocket": {
    "_event": "pickpocket",
    "sfx": "none",
    "icon": "Inv_misc_bag_11",
    "cooldown": 30,
    "id": "abil_pickpocket",
    "hpmod_p": false,
    "animation": "unarmed",
    "target": "self",
    "clas": "scout",
    "casttime": 0,
    "effects": [],
    "name": "Pick Pocket",
    "cost": 0,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 9,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$cooldown round cooldown<br>Pick the target's pocket.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 90
  },
  "abil_adrenrush": {
    "_event": "none",
    "sfx": "adrenrush",
    "icon": "Spell_shadow_shadowworddominate",
    "cooldown": 160,
    "id": "abil_adrenrush",
    "hpmod_p": false,
    "animation": "idle",
    "target": "self",
    "clas": "scout",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_adrenrush"
      }
    ],
    "name": "Adrenaline Rush",
    "cost": 10,
    "incombat": true,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 36,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$cooldown round cooldown<br>Restores 100 Energy over 10 rounds.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 360
  },
  "abil_cheese": {
    "_event": "none",
    "sfx": "food",
    "icon": "none",
    "cooldown": 2,
    "id": "abil_cheese",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Old Cheese",
    "cost": 0,
    "incombat": false,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 50,
    "scooldown": "food",
    "desc": "Restores $hpmod health. ($cooldown round cooldown)",
    "hpmodmax": 70,
    "type": "skill",
    "val": 0
  },
  "abil_quillboar_headbutt": {
    "_event": "none",
    "sfx": "none",
    "icon": "none",
    "cooldown": 4,
    "id": "abil_quillboar_headbutt",
    "hpmod_p": false,
    "animation": "headbutt",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_quillboar_headbutt"
      }
    ],
    "name": "Headbutt",
    "cost": 0,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": -5,
    "scooldown": "none",
    "desc": "",
    "hpmodmax": -5,
    "type": "skill",
    "val": 0
  },
  "abil_carrion_screech": {
    "_event": "none",
    "sfx": "none",
    "cost_p": false,
    "cooldown": 5,
    "id": "abil_carrion_screech",
    "hpmod_p": false,
    "animation": "special",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_carrion_screech"
      }
    ],
    "name": "Demoralizing Screech",
    "cost": 0,
    "incombat": true,
    "icon": "none",
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "",
    "hpmodmax": 0,
    "type": "skill",
    "val": 0
  },
  "abil_brandy": {
    "_event": "none",
    "sfx": "drink",
    "icon": "none",
    "cooldown": 0,
    "id": "abil_brandy",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_brandy"
      }
    ],
    "name": "Snowplum Brandy",
    "cost": 0,
    "incombat": false,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 100,
    "scooldown": "food",
    "desc": "Restores $hpmod health and increases strength by 5 for 60 rounds.",
    "hpmodmax": 180,
    "type": "skill",
    "val": 0
  },
  "abil_flameshock": {
    "_event": "none",
    "sfx": "flameshock",
    "icon": "Spell_fire_flameshock",
    "cooldown": 2,
    "id": "abil_flameshock",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "shaman",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_flameshock"
      }
    ],
    "name": "Flame Shock",
    "cost": -17,
    "incombat": true,
    "cost_p": true,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 12,
    "hpmodmin": -25,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$cooldown round cooldown<br>Sears the target with fire, causing $hpmod damage and an additional 50 damage over 5 rounds.",
    "hpmodmax": -25,
    "type": "spell",
    "val": 120
  },
  "abil_curedisease": {
    "_event": "none",
    "sfx": "cure",
    "icon": "Spell_nature_removedisease",
    "cooldown": 5,
    "id": "abil_curedisease",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": -1,
    "effects": [],
    "name": "Cure Disease",
    "cost": -7,
    "incombat": true,
    "cost_p": true,
    "outcombat": true,
    "cures": "disease",
    "no_scale": false,
    "level": 3,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$cooldown round cooldown<br>Instantly cures 1 disease effect.",
    "hpmodmax": 0,
    "type": "spell",
    "val": 30
  },
  "abil_giantegg": {
    "_event": "none",
    "sfx": "food",
    "icon": "none",
    "cooldown": 0,
    "id": "abil_giantegg",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_giantegg"
      }
    ],
    "name": "Giant Egg",
    "cost": 0,
    "incombat": false,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 70,
    "scooldown": "food",
    "desc": "Restores $hpmod health and increases stamina by 3 for 60 rounds.",
    "hpmodmax": 100,
    "type": "skill",
    "val": 0
  },
  "abil_curepoison": {
    "_event": "none",
    "sfx": "cure",
    "icon": "Spell_nature_nullifypoison",
    "cooldown": 5,
    "id": "abil_curepoison",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": -1,
    "effects": [],
    "name": "Cure Poison",
    "cost": -7,
    "incombat": true,
    "cost_p": true,
    "outcombat": true,
    "cures": "poison",
    "no_scale": false,
    "level": 15,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$cooldown round cooldown<br>Instantly cures 1 poison effect.",
    "hpmodmax": 0,
    "type": "spell",
    "val": 150
  },
  "abil_quillboar_attack": {
    "_event": "none",
    "sfx": "none",
    "icon": "none",
    "cooldown": 0,
    "id": "abil_quillboar_attack",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Attack",
    "cost": 0,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 1,
    "hpmodmin": -3,
    "scooldown": "none",
    "desc": "",
    "hpmodmax": -5,
    "type": "skill",
    "val": 0
  },
  "abil_hex": {
    "_event": "none",
    "sfx": "hex",
    "icon": "Spell_shaman_hex",
    "cooldown": 45,
    "id": "abil_hex",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "shaman",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_hex"
      }
    ],
    "name": "Hex",
    "cost": -12,
    "incombat": true,
    "cost_p": true,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 27,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$cooldown round cooldown<br>Transforms the target into a frog for 5 rounds. While hexed, the target cannot attack or cast spells.",
    "hpmodmax": 0,
    "type": "spell",
    "val": 270
  },
  "abil_colsmash": {
    "_event": "none",
    "sfx": "colsmash",
    "icon": "ability_warrior_colossussmash",
    "cooldown": 2,
    "id": "abil_colsmash",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "barbarian",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_colsmash"
      }
    ],
    "name": "Colossus Smash",
    "cost": -50,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 36,
    "hpmodmin": -40,
    "scooldown": "none",
    "desc": "$powmod Rage<br>$cooldown round cooldown<br>An attack that deals $hpmod damage and stuns the target for the next round.",
    "hpmodmax": -50,
    "type": "skill",
    "val": 360
  },
  "abil_slam": {
    "hpmod_p": false,
    "sfx": "slam",
    "cost_p": false,
    "cooldown": 0,
    "id": "abil_slam",
    "_event": "none",
    "animation": "default",
    "target": "enemy",
    "clas": "barbarian",
    "casttime": 1,
    "effects": [],
    "name": "Slam",
    "level": 15,
    "incombat": true,
    "icon": "Ability_warrior_decisivestrike",
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "cost": -40,
    "hpmodmin": -43,
    "scooldown": "none",
    "desc": "$powmod Rage<br>$casttime round cast<br>Slams the opponent, causing $hpmod damage.",
    "hpmodmax": -49,
    "type": "skill",
    "val": 150
  },
  "abil_item_roastboar": {
    "_event": "none",
    "sfx": "food",
    "icon": "none",
    "cooldown": 2,
    "id": "abil_item_roastboar",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Roasted Boar Meat",
    "cost": 0,
    "incombat": false,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 90,
    "scooldown": "food",
    "desc": "Restores $hpmod health. ($cooldown round cooldown)",
    "hpmodmax": 120,
    "type": "skill",
    "val": 0
  },
  "abil_battleshout": {
    "_event": "none",
    "sfx": "battleshout",
    "icon": "Ability_warrior_battleshout",
    "cooldown": 120,
    "id": "abil_battleshout",
    "hpmod_p": false,
    "animation": "idle",
    "target": "self",
    "clas": "barbarian",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_battleshout"
      }
    ],
    "name": "Battle Shout",
    "cost": 20,
    "incombat": true,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 12,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$cooldown round cooldown<br>Generates $powmod rage and increases strength and agility by 17 for 120 rounds.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 120
  },
  "abil_ghostwolf": {
    "_event": "none",
    "sfx": "ghostwolf",
    "icon": "Spell_nature_spiritwolf",
    "cooldown": 30,
    "id": "abil_ghostwolf",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_ghostwolf"
      }
    ],
    "name": "Ghost Wolf",
    "cost": -6,
    "incombat": false,
    "cost_p": true,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 21,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$cooldown round cooldown<br>Turns the Shaman into a Ghost Wolf, increasing Mana regeneration by 150%. Effect disappears in combat.",
    "hpmodmax": 0,
    "type": "spell",
    "val": 210
  },
  "abil_rend": {
    "_event": "none",
    "sfx": "rend",
    "icon": "Ability_gouge",
    "cooldown": 0,
    "id": "abil_rend",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "barbarian",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_rend"
      }
    ],
    "name": "Rend",
    "cost": -5,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 3,
    "hpmodmin": -1,
    "scooldown": "none",
    "desc": "$powmod Rage<br>An attack that deals $hpmod damage causing the target to bleed for an additional 60 damage over 6 rounds.",
    "hpmodmax": -3,
    "type": "skill",
    "val": 30
  },
  "abil_attack": {
    "_event": "none",
    "sfx": "attack",
    "icon": "Ability_meleedamage",
    "cooldown": 0,
    "id": "abil_attack",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Attack",
    "cost": 0,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 1,
    "hpmodmin": -1,
    "scooldown": "none",
    "desc": "Attack with your weapon for $hpmod damage.",
    "hpmodmax": -3,
    "type": "skill",
    "val": 0
  },
  "abil_cheapshot": {
    "_event": "none",
    "sfx": "cheapshot",
    "icon": "Ability_cheapshot",
    "cooldown": 6,
    "id": "abil_cheapshot",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "scout",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_cheapshot"
      }
    ],
    "name": "Cheap Shot",
    "cost": -40,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "level": 18,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod Energy<br>$cooldown round cooldown<br>Stuns the target for 2 rounds.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 180
  },
  "abil_elemoath": {
    "_event": "none",
    "sfx": "elemoath",
    "icon": "Spell_shaman_elementaloath",
    "cooldown": 240,
    "id": "abil_elemoath",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": -1,
    "effects": [
      {
        "value": "eff_elemoath"
      }
    ],
    "name": "Elemental Oath",
    "cost": -5,
    "incombat": true,
    "cost_p": true,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 30,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$cooldown round cooldown<br>Instantly increases strength, agility, stamina and intelligence by 20 for 240 rounds.",
    "hpmodmax": 0,
    "type": "spell",
    "val": 300
  },
  "abil_recklessness": {
    "_event": "none",
    "sfx": "recklessness",
    "icon": "Ability_criticalstrike",
    "cooldown": 120,
    "id": "abil_recklessness",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "barbarian",
    "casttime": -1,
    "effects": [
      {
        "value": "eff_recklessness"
      }
    ],
    "name": "Recklessness",
    "cost": 0,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 30,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$cooldown round cooldown<br>Instantly grants your melee attacks an additional 60% chance to critically hit but increases their chance to miss by 10%. Lasts for 6 rounds.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 300
  },
  "abil_sweetpotato": {
    "_event": "none",
    "sfx": "food",
    "icon": "none",
    "cooldown": 0,
    "id": "abil_sweetpotato",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Sweet Potato",
    "cost": 0,
    "incombat": false,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 80,
    "scooldown": "food",
    "desc": "Restores $hpmod health.",
    "hpmodmax": 110,
    "type": "skill",
    "val": 0
  },
  "abil_bloodlust": {
    "_event": "none",
    "sfx": "bloodlust",
    "icon": "Spell_nature_bloodlust",
    "cooldown": 120,
    "id": "abil_bloodlust",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": -1,
    "effects": [
      {
        "value": "eff_bloodlust"
      }
    ],
    "name": "Bloodlust",
    "cost": -26,
    "incombat": true,
    "cost_p": true,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 18,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$cooldown round cooldown<br>Instantly increases spell and melee critical chance by 10% for 120 rounds.",
    "hpmodmax": 0,
    "type": "spell",
    "val": 180
  },
  "abil_key": {
    "_event": "key",
    "sfx": "none",
    "icon": "none",
    "cooldown": 2,
    "id": "abil_key",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Skeleton Key",
    "cost": 0,
    "incombat": false,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "Unlocks any chest. One time use.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 0
  },
  "abil_pummel": {
    "_event": "none",
    "sfx": "pummel",
    "icon": "Inv_gauntlets_04",
    "cooldown": 6,
    "id": "abil_pummel",
    "hpmod_p": false,
    "animation": "unarmed",
    "target": "enemy",
    "clas": "barbarian",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_pummel"
      }
    ],
    "name": "Pummel",
    "cost": -20,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 9,
    "hpmodmin": -1,
    "scooldown": "none",
    "desc": "$powmod Rage<br>$cooldown round cooldown<br>An attack that deals $hpmod damage and silences the target for 4 rounds.",
    "hpmodmax": -3,
    "type": "skill",
    "val": 90
  },
  "abil_bloodrage": {
    "_event": "none",
    "sfx": "bloodrage",
    "icon": "Ability_racial_bloodrage",
    "cooldown": 3,
    "id": "abil_bloodrage",
    "hpmod_p": true,
    "animation": "default",
    "target": "self",
    "clas": "barbarian",
    "casttime": -1,
    "effects": [],
    "name": "Blood Rage",
    "cost": 20,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 6,
    "hpmodmin": -20,
    "scooldown": "none",
    "desc": "$cooldown round cooldown<br>Instantly generates $powmod rage at the cost of $hpmod base health.",
    "hpmodmax": -20,
    "type": "skill",
    "val": 60
  },
  "abil_healsurge": {
    "_event": "none",
    "sfx": "heal",
    "icon": "Spell_nature_healingway",
    "cooldown": 0,
    "id": "abil_healsurge",
    "hpmod_p": true,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": 3,
    "effects": [],
    "name": "Healing Surge",
    "cost": -45,
    "incombat": true,
    "cost_p": true,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 15,
    "hpmodmin": 100,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$casttime round cast<br>Restores 100% of base health.",
    "hpmodmax": 100,
    "type": "spell",
    "val": 150
  },
  "abil_pumpkin": {
    "_event": "none",
    "sfx": "food",
    "icon": "none",
    "cooldown": 0,
    "id": "abil_pumpkin",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Country Pumpkin",
    "cost": 0,
    "incombat": false,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 140,
    "scooldown": "food",
    "desc": "Restores $hpmod health.",
    "hpmodmax": 200,
    "type": "skill",
    "val": 0
  },
  "abil_rcopperbomb": {
    "hpmod_p": false,
    "sfx": "explosion",
    "cost_p": false,
    "cooldown": 10,
    "id": "abil_rcopperbomb",
    "_event": "none",
    "animation": "unarmed",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Rough Copper Bomb",
    "level": 1,
    "incombat": true,
    "icon": "none",
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "cost": 0,
    "hpmodmin": -22,
    "scooldown": "bomb",
    "desc": "Inflicts $hpmod damage. ($cooldown round cooldown)",
    "hpmodmax": -28,
    "type": "skill",
    "val": 0
  },
  "abil_healrain": {
    "_event": "none",
    "sfx": "healrain",
    "icon": "Spell_nature_giftofthewaterspirit",
    "cooldown": 60,
    "id": "abil_healrain",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_healrain"
      }
    ],
    "name": "Healing Rain",
    "cost": -46,
    "incombat": true,
    "cost_p": true,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 36,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$powmod of base Mana<br>$cooldown round cooldown<br>Calls forth healing rains to blanket the Shaman, restoring 4000 health over 10 rounds.",
    "hpmodmax": 0,
    "type": "spell",
    "val": 360
  },
  "abil_picklock": {
    "_event": "picklock",
    "sfx": "none",
    "icon": "Spell_nature_moonkey",
    "cooldown": 30,
    "id": "abil_picklock",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "scout",
    "casttime": -1,
    "effects": [],
    "name": "Pick Lock",
    "cost": 0,
    "incombat": false,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 12,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$cooldown round cooldown<br>Instantly opens any locked chest up to the Scout's level.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 120
  },
  "abil_intercept": {
    "_event": "none",
    "sfx": "intercept",
    "icon": "Ability_rogue_sprint",
    "cooldown": 10,
    "id": "abil_intercept",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "barbarian",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_intercept"
      }
    ],
    "name": "Intercept",
    "cost": -10,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 21,
    "hpmodmin": -5,
    "scooldown": "none",
    "desc": "$powmod Rage<br>$cooldown round cooldown<br>Charge an enemy, causing $hpmod damage and stunning it for 3 rounds.",
    "hpmodmax": -5,
    "type": "skill",
    "val": 210
  },
  "abil_lesserhealpot": {
    "hpmod_p": false,
    "sfx": "potion",
    "desc": "Instantly restores $hpmod health. ($cooldown round cooldown)",
    "cooldown": 6,
    "id": "abil_lesserhealpot",
    "_event": "none",
    "animation": "default",
    "target": "self",
    "clas": "default",
    "casttime": -1,
    "effects": [],
    "name": "Lesser Healing Potion",
    "level": 1,
    "incombat": true,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "cost": 0,
    "hpmodmin": 140,
    "scooldown": "potion",
    "icon": "none",
    "hpmodmax": 180,
    "type": "skill",
    "val": 0
  },
  "abil_backstab": {
    "_event": "none",
    "sfx": "backstab",
    "icon": "Ability_backstab",
    "cooldown": 0,
    "id": "abil_backstab",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "scout",
    "casttime": 0,
    "effects": [],
    "name": "Backstab",
    "cost": -60,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 12,
    "hpmodmin": -40,
    "scooldown": "none",
    "desc": "$powmod Energy<br>Backstab the target, causing $hpmod damage.",
    "hpmodmax": -60,
    "type": "skill",
    "val": 120
  },
  "abil_arcanebomb": {
    "hpmod_p": false,
    "sfx": "explosion",
    "desc": "Inflicts $hpmod damage and silences the target for 3 rounds. ($cooldown round cooldown)",
    "cooldown": 10,
    "id": "abil_arcanebomb",
    "_event": "none",
    "animation": "unarmed",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [
      {
        "value": "eff_arcanebomb"
      }
    ],
    "name": "Arcane Bomb",
    "level": 1,
    "incombat": true,
    "icon": "none",
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "cost": 0,
    "hpmodmin": -5,
    "scooldown": "bomb",
    "cost_p": false,
    "hpmodmax": -10,
    "type": "skill",
    "val": 0
  },
  "abil_tarpdew": {
    "_event": "none",
    "sfx": "drink",
    "icon": "none",
    "cooldown": 0,
    "id": "abil_tarpdew",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": 0,
    "effects": [],
    "name": "Tarp Collected Dew",
    "cost": 80,
    "incombat": false,
    "cost_p": false,
    "outcombat": true,
    "cures": "none",
    "no_scale": true,
    "level": 1,
    "hpmodmin": 0,
    "scooldown": "food",
    "desc": "Restores $powmod Mana.",
    "hpmodmax": 0,
    "type": "skill",
    "val": 0
  },
  "abil_manaspring": {
    "_event": "none",
    "sfx": "manaspring",
    "icon": "Spell_arcane_arcane02",
    "cooldown": 60,
    "id": "abil_manaspring",
    "hpmod_p": false,
    "animation": "default",
    "target": "self",
    "clas": "shaman",
    "casttime": -1,
    "effects": [
      {
        "value": "eff_manaspring"
      }
    ],
    "name": "Mana Spring",
    "cost": 20,
    "incombat": true,
    "cost_p": true,
    "outcombat": true,
    "cures": "none",
    "no_scale": false,
    "level": 9,
    "hpmodmin": 0,
    "scooldown": "none",
    "desc": "$cooldown round cooldown<br>Instantly restores 20% of base Mana and an additional 100 Mana over 5 rounds.",
    "hpmodmax": 0,
    "type": "spell",
    "val": 90
  },
  "abil_herostrike": {
    "_event": "none",
    "sfx": "herostrike",
    "icon": "Ability_rogue_ambush",
    "cooldown": 0,
    "id": "abil_herostrike",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "barbarian",
    "casttime": 0,
    "effects": [],
    "name": "Heroic Strike",
    "cost": -30,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 1,
    "hpmodmin": -20,
    "scooldown": "none",
    "desc": "$powmod Rage<br>An attack that deals $hpmod damage.",
    "hpmodmax": -30,
    "type": "skill",
    "val": 0
  },
  "abil_bigone": {
    "hpmod_p": false,
    "sfx": "big_explosion",
    "desc": "Inflicts $hpmod damage. ($cooldown round cooldown)",
    "cooldown": 60,
    "id": "abil_bigone",
    "_event": "none",
    "animation": "unarmed",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "The Big One",
    "level": 1,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": true,
    "cost": 0,
    "hpmodmin": -100,
    "scooldown": "none",
    "icon": "none",
    "hpmodmax": -200,
    "type": "skill",
    "val": 0
  },
  "abil_mon_attack": {
    "_event": "none",
    "sfx": "none",
    "icon": "none",
    "cooldown": 0,
    "id": "abil_mon_attack",
    "hpmod_p": false,
    "animation": "default",
    "target": "enemy",
    "clas": "default",
    "casttime": 0,
    "effects": [],
    "name": "Attack",
    "cost": 0,
    "incombat": true,
    "cost_p": false,
    "outcombat": false,
    "cures": "none",
    "no_scale": false,
    "level": 1,
    "hpmodmin": -1,
    "scooldown": "none",
    "desc": "",
    "hpmodmax": -4,
    "type": "skill",
    "val": 0
  }
}`;
