        const effectDBJSON = `
{
  "eff_shieldwall": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_shieldwall",
    "sphit": 0,
    "polymorph": "none",
    "stats": [
      {
        "stat": "sta",
        "num": 30
      }
    ],
    "rounds": 480,
    "silence": false,
    "name": "Shield Wall",
    "hpmod": 0,
    "stun": false,
    "icon": "Ability_warrior_shieldwall",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_manaspring": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_manaspring",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 5,
    "silence": false,
    "name": "Mana Spring",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_arcane_arcane02",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 20,
    "pdodge": 0,
    "type": "general"
  },
  "eff_ressickness2": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_ressickness2",
    "sphit": 0,
    "polymorph": "none",
    "stats": [
      {
        "stat": "str",
        "num": -12
      },
      {
        "stat": "agi",
        "num": -12
      },
      {
        "stat": "sta",
        "num": -12
      },
      {
        "stat": "int",
        "num": -12
      }
    ],
    "rounds": 60,
    "silence": false,
    "name": "Resurrection Sickness",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_shadow_deathscream",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_greed": {
    "pcrit": 4,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_greed",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 0,
    "silence": false,
    "name": "Greed",
    "hpmod": 0,
    "stun": false,
    "icon": "Inv_weapon_hand_06",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_cheapshot": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_cheapshot",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 3,
    "silence": false,
    "name": "Cheap Shot",
    "hpmod": 0,
    "stun": true,
    "icon": "Ability_cheapshot",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_brandy": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_brandy",
    "sphit": 0,
    "polymorph": "none",
    "stats": [
      {
        "stat": "str",
        "num": 5
      }
    ],
    "rounds": 60,
    "silence": false,
    "name": "Snowplum Brandy",
    "hpmod": 0,
    "stun": false,
    "icon": "Inv_drink_02",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_recuperate": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_recuperate",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 6,
    "silence": false,
    "name": "Recuperate",
    "hpmod": 50,
    "stun": false,
    "icon": "Ability_rogue_recuperate",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_vigcharm": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_vigcharm",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 0,
    "silence": false,
    "name": "Vigilance Charm",
    "hpmod": 0,
    "stun": false,
    "icon": "Inv_misc_stonetablet_04",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 3,
    "type": "general"
  },
  "eff_ressickness3": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_ressickness3",
    "sphit": 0,
    "polymorph": "none",
    "stats": [
      {
        "stat": "str",
        "num": -16
      },
      {
        "stat": "agi",
        "num": -16
      },
      {
        "stat": "sta",
        "num": -16
      },
      {
        "stat": "int",
        "num": -16
      }
    ],
    "rounds": 60,
    "silence": false,
    "name": "Resurrection Sickness",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_shadow_deathscream",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_evasion": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_evasion",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 8,
    "silence": false,
    "name": "Evasion",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_shadow_shadowward",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 50,
    "type": "general"
  },
  "eff_flashbomb": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_flashbomb",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 3,
    "silence": false,
    "name": "Flash Bomb",
    "hpmod": 0,
    "stun": true,
    "icon": "Inv_misc_ammo_bullet_01",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_blackcutlass": {
    "pcrit": 0,
    "phit": 4,
    "spcrit": 0,
    "id": "eff_blackcutlass",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 0,
    "silence": false,
    "name": "Blackwater Cutlass",
    "hpmod": 0,
    "stun": false,
    "icon": "Inv_sword_24",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_quillboar_headbutt": {
    "pcrit": 0,
    "phit": -60,
    "spcrit": 0,
    "id": "eff_quillboar_headbutt",
    "sphit": -60,
    "polymorph": "none",
    "stats": [],
    "rounds": 3,
    "silence": false,
    "name": "Headbutt",
    "hpmod": 0,
    "stun": false,
    "icon": "Ability_hunter_pet_boar",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_carrion_screech": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_carrion_screech",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 3,
    "silence": false,
    "name": "Cower",
    "hpmod": 0,
    "stun": true,
    "icon": "Ability_druid_cower",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_healrain": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_healrain",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 10,
    "silence": false,
    "name": "Healing Rain",
    "hpmod": 400,
    "stun": false,
    "icon": "Spell_nature_giftofthewaterspirit",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_intercept": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_intercept",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 3,
    "silence": false,
    "name": "Intercept",
    "hpmod": 0,
    "stun": true,
    "icon": "Ability_rogue_sprint",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_bloodlust": {
    "pcrit": 10,
    "phit": 0,
    "spcrit": 10,
    "id": "eff_bloodlust",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 120,
    "silence": false,
    "name": "Bloodlust",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_nature_bloodlust",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_ancspirit": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_ancspirit",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 300,
    "silence": false,
    "name": "Ancestral Spirit",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_nature_regenerate",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_slicedice": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_slicedice",
    "sphit": 0,
    "polymorph": "none",
    "stats": [
      {
        "stat": "agi",
        "num": 20
      }
    ],
    "rounds": 240,
    "silence": false,
    "name": "Slice and Dice",
    "hpmod": 0,
    "stun": false,
    "icon": "Ability_rogue_slicedice",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_elemoath": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_elemoath",
    "sphit": 0,
    "polymorph": "none",
    "stats": [
      {
        "stat": "str",
        "num": 20
      },
      {
        "stat": "agi",
        "num": 20
      },
      {
        "stat": "sta",
        "num": 20
      },
      {
        "stat": "int",
        "num": 20
      }
    ],
    "rounds": 240,
    "silence": false,
    "name": "Elemental Oath",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_shaman_elementaloath",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_arcanebomb": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_arcanebomb",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 3,
    "silence": true,
    "name": "Arcane Bomb",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_shadow_mindbomb",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_adrenrush": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_adrenrush",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 10,
    "silence": false,
    "name": "Adrenaline Rush",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_shadow_shadowworddominate",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 10,
    "pdodge": 0,
    "type": "general"
  },
  "eff_pummel": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_pummel",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 4,
    "silence": true,
    "name": "Pummel",
    "hpmod": 0,
    "stun": false,
    "icon": "Inv_gauntlets_04",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_battleshout": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_battleshout",
    "sphit": 0,
    "polymorph": "none",
    "stats": [
      {
        "stat": "str",
        "num": 17
      },
      {
        "stat": "agi",
        "num": 17
      }
    ],
    "rounds": 120,
    "silence": false,
    "name": "Battle Shout",
    "hpmod": 0,
    "stun": false,
    "icon": "Ability_warrior_battleshout",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_infectedwound": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_infectedwound",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 5,
    "silence": false,
    "name": "Infected Wound",
    "hpmod": -5,
    "stun": false,
    "icon": "Spell_nature_nullifydisease",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "disease"
  },
  "eff_kick": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_kick",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 4,
    "silence": true,
    "name": "Sucker Punch",
    "hpmod": 0,
    "stun": false,
    "icon": "Inv_gauntlets_21",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_frogband": {
    "pcrit": 4,
    "phit": 0,
    "spcrit": 4,
    "id": "eff_frogband",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 0,
    "silence": false,
    "name": "Frog-Toe Band",
    "hpmod": 0,
    "stun": false,
    "icon": "Inv_jewelry_ring_44",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_giantegg": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_giantegg",
    "sphit": 0,
    "polymorph": "none",
    "stats": [
      {
        "stat": "sta",
        "num": 3
      }
    ],
    "rounds": 60,
    "silence": false,
    "name": "Giant Egg",
    "hpmod": 0,
    "stun": false,
    "icon": "Inv_egg_03",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_kidneyshot": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_kidneyshot",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 4,
    "silence": false,
    "name": "Kidney Shot",
    "hpmod": 0,
    "stun": true,
    "icon": "Ability_rogue_kidneyshot",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_enragedregen": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_enragedregen",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 10,
    "silence": false,
    "name": "Enraged Regeneration",
    "hpmod": 50,
    "stun": false,
    "icon": "Ability_warrior_focusedrage",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_ressickness4": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_ressickness4",
    "sphit": 0,
    "polymorph": "none",
    "stats": [
      {
        "stat": "str",
        "num": -20
      },
      {
        "stat": "agi",
        "num": -20
      },
      {
        "stat": "sta",
        "num": -20
      },
      {
        "stat": "int",
        "num": -20
      }
    ],
    "rounds": 60,
    "silence": false,
    "name": "Resurrection Sickness",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_shadow_deathscream",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_ringprec": {
    "pcrit": 0,
    "phit": 20,
    "spcrit": 0,
    "id": "eff_ringprec",
    "sphit": 20,
    "polymorph": "none",
    "stats": [],
    "rounds": 0,
    "silence": false,
    "name": "Ring of Precision",
    "hpmod": 0,
    "stun": false,
    "icon": "Inv_jewelry_ring_14",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_elemshield": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_elemshield",
    "sphit": 0,
    "polymorph": "none",
    "stats": [
      {
        "stat": "sta",
        "num": 10
      },
      {
        "stat": "int",
        "num": 10
      }
    ],
    "rounds": 240,
    "silence": false,
    "name": "Elemental Shield",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_nature_lightningshield",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_ressickness1": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_ressickness1",
    "sphit": 0,
    "polymorph": "none",
    "stats": [
      {
        "stat": "str",
        "num": -8
      },
      {
        "stat": "agi",
        "num": -8
      },
      {
        "stat": "sta",
        "num": -8
      },
      {
        "stat": "int",
        "num": -8
      }
    ],
    "rounds": 30,
    "silence": false,
    "name": "Resurrection Sickness",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_shadow_deathscream",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_frostshock": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_frostshock",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 2,
    "silence": false,
    "name": "Frost Shock",
    "hpmod": 0,
    "stun": true,
    "icon": "Spell_frost_frostshock",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_andonisus": {
    "pcrit": 10,
    "phit": 0,
    "spcrit": 10,
    "id": "eff_andonisus",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 0,
    "silence": false,
    "name": "Andonisus",
    "hpmod": 0,
    "stun": false,
    "icon": "Inv_sword_61",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_mon_hex": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_mon_hex",
    "sphit": 0,
    "polymorph": "mon_frog",
    "stats": [],
    "rounds": 3,
    "silence": false,
    "name": "Hex",
    "hpmod": 0,
    "stun": true,
    "icon": "Spell_shaman_hex",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_ghostwolf": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_ghostwolf",
    "sphit": 0,
    "polymorph": "mon_ghostwolf",
    "stats": [],
    "rounds": 0,
    "silence": false,
    "name": "Ghost Wolf",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_nature_spiritwolf",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 30,
    "pdodge": 0,
    "type": "general"
  },
  "eff_colsmash": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_colsmash",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 2,
    "silence": false,
    "name": "Colossus Smash",
    "hpmod": 0,
    "stun": true,
    "icon": "ability_warrior_colossussmash",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_recklessness": {
    "pcrit": 60,
    "phit": -10,
    "spcrit": 0,
    "id": "eff_recklessness",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 6,
    "silence": false,
    "name": "Recklessness",
    "hpmod": 0,
    "stun": false,
    "icon": "Ability_criticalstrike",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_healwave": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_healwave",
    "sphit": 0,
        "polymorph": "none",
    "stats": [],
    "rounds": 5,
    "silence": false,
    "name": "Healing Wave",
    "hpmod": 10,
    "stun": false,
    "icon": "Spell_nature_magicimmunity",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_warbringer": {
    "pcrit": 0,
    "phit": 10,
    "spcrit": 0,
    "id": "eff_warbringer",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 0,
    "silence": false,
    "name": "Warbringer",
    "hpmod": 0,
    "stun": false,
    "icon": "Inv_axe_10",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 10,
    "type": "general"
  },
  "eff_lifestone": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_lifestone",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 0,
    "silence": false,
    "name": "Lifestone",
    "hpmod": 5,
    "stun": false,
    "icon": "Inv_ore_truesilver_01",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_rend": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_rend",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 6,
    "silence": false,
    "name": "Bleed",
    "hpmod": -10,
    "stun": false,
    "icon": "Ability_gouge",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_berserkrage": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_berserkrage",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 5,
    "silence": false,
    "name": "Berserker Rage",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_nature_ancestralguardian",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 10,
    "pdodge": 0,
    "type": "general"
  },
  "eff_hex": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_hex",
    "sphit": 0,
    "polymorph": "mon_frog",
    "stats": [],
    "rounds": 5,
    "silence": false,
    "name": "Hex",
    "hpmod": 0,
    "stun": true,
    "icon": "Spell_shaman_hex",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "curse"
  },
  "eff_flameshock": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_flameshock",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 5,
    "silence": false,
    "name": "Flame Shock",
    "hpmod": -10,
    "stun": false,
    "icon": "Spell_fire_flameshock",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_coldblood": {
    "pcrit": 100,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_coldblood",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 1,
    "silence": false,
    "name": "Cold Blood",
    "hpmod": 0,
    "stun": false,
    "icon": "Spell_ice_lament",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_bandvigor": {
    "pcrit": 2,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_bandvigor",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 0,
    "silence": false,
    "name": "Band of Vigor",
    "hpmod": 0,
    "stun": false,
    "icon": "Inv_jewelry_ring_20",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  },
  "eff_garrote": {
    "pcrit": 0,
    "phit": 0,
    "spcrit": 0,
    "id": "eff_garrote",
    "sphit": 0,
    "polymorph": "none",
    "stats": [],
    "rounds": 20,
    "silence": false,
    "name": "Garrote",
    "hpmod": -50,
    "stun": false,
    "icon": "Ability_rogue_garrote",
    "pheal": 0,
    "pdmg": 0,
    "powermod": 0,
    "pdodge": 0,
    "type": "general"
  }
}`;